### ISSUE TITLE
vmm: openapi: the value of `initramfs` defaults to empty string ("") as its path 

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#1015]
As an optional  property of `VmConfig` to boot VM, the default value of the `initramfs` is an empty string `""` as its path, e.g. `"initramfs":{"path":""}`. This causes `clh` to report error while `VmBoot`: `"No such file or directory"`.

**Comment by rbradford** [comment]
So the problem is that embedded structs cannot have an "empty" value so "omitempty" has no meaning. Ideally the generated code would use a pointer (which can have an empty value of nil) for embedded structs. https://www.sohamkamani.com/golang/2018-07-19-golang-omitempty/

To me: https://goswagger.io/use/schemas.html would imply this should be made a pointer. But I guess you're not using go-swagger but something else: openapi-generator. Apparently `nullable: true` would make it a pointer.
