### ISSUE TITLE
virtio-scsi support

### ISSUE THREAD

**Issue by kylecarbs** [cloud-hypervisor/cloud-hypervisor#1073]
Does cloud-hypervisor support [virtio-scsi](https://www.ovirt.org/develop/release-management/features/storage/virtio-scsi.html)? I don't see it in the docs.

I need to dynamically mount a lot of separate points, hotplugging virtio-fs hits the limit on PCI devices.

**Comment by sboeuf** [comment]
No, there's no `virtio-scsi` support in Cloud-Hypervisor, which would allow you avoid hitting the PCI device limit.

You could use a different approach by using a single `virtio-fs` device for the entire VM, and all your dynamic mounts would be new mount points into the shared directory that you already shared through `virtio-fs`.
Do you think this could work for you?

**Comment by kylecarbs** [comment]
Mounting in the shared dir doesn't propagate the files to the guest. Here's what I tried:

1. Create shared dir between the host and guest at `/mnt`.
2. `mkdir /mnt/shared`
3. Ensure `/mnt/shared` exists in the host and guest.
4. On the host: `mount -o bind /shared /mnt/shared`
5. The `shared` dir exists on both, but contents only appear on the host.

**Comment by sboeuf** [comment]
It works for me. I tested with both `virtiofsd` (C) and `vhost-user-fs` (rust) backends.
1. Start the VM with a `virtio-fs` device. My shared directory is at `/home/sebastien/mount_dir` and contains a directory `test` with two files (`test6` and `test7`).
2. Mount the filesystem inside the VM: `mount -t virtiofs -o dax myfs /mnt`
3. Check what's in `/mnt/test`
```
# cat /mnt/test
test6  test7
```
4. From the host, create a directory `test_dir` with `bind_file_1` file in there.
5. From the host, bind mount the directory `test_dir` into `/home/sebastien/mount_dir/test`
```
$ sudo mount -o bind test_dir/ /home/sebastien/mount_dir/test/
```
6. From the guest check what's in `/mnt/test`
```
# cat /mnt/test
bind_file_1
```

So that's what's expected as you can see the content being updated.

In your case, that means every time you want to dynamically add something, you would create an empty directory inside the shared directory and you would bind mount your actual data into this new directory.

**Comment by kylecarbs** [comment]
Hm not sure what's going on here. Thanks for testing it out!

I'll debug on my end.

**Comment by kylecarbs** [comment]
In my testing I wasn't using `dax`. I'll update if that breaks the bind situation.

In other findings, `dax` doesn't work on a hotplugged filesystem. Might be better to create a new issue for this, but any immediate ideas?

**Comment by sboeuf** [comment]
@kylecarbs could you please detail all the steps your going through and the exact command line you're using for each of your components?
I'm asking because on my side, based on master, I can use `dax` on a hotplugged filesystem, and then I can perform the bind mount.

**Comment by kylecarbs** [comment]
I'm using the HTTP API, but I'll provide some details.

**Comment by kylecarbs** [comment]
Found the issue. The source of the virtiofsd was inside an overlayfs. I guess it won't follow bind mounts inside an overlay.

**Comment by sboeuf** [comment]
Oh yes if you're bind mounting on top of an overlay, then this is the behavior you get. That's why you should always have a shared directory that's not based off an overlay, but if you want to have access to the information from the overlay, you can bind mount them into the shared directory.

I think this issue can be closed now. Feel free to reopen if I missed something.
