### ISSUE TITLE
Thread 'vcpu' panic when rebooting VM 235 times

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#1124]
I am not sure whether this is a bug, but I can constantly hit the following error when rebooting the VM 235 times with a very plain VM config:
```
thread 'vcpu0' panicked at 'Failed to activate device: BadActivate', vm-virtio/src/transport/pci_device.rs:910:21
```

It was first observed while testing PR #1111, and I confirmed it is still reproducible on [latest master branch](https://github.com/cloud-hypervisor/cloud-hypervisor/commit/9adc32a04343db23bb6f7d8b4e349127928410d5). The script to reproduce the error:
```
#!/bin/bash

set -e

/home/chenb/project/cloud-hypervisor/cloud-hypervisor/target/debug/cloud-hypervisor \
    --kernel /home/chenb/project/cloud-hypervisor/rust-hypervisor-firmware/target/target/release/hypervisor-fw \
    --disk path=/home/chenb/project/cloud-hypervisor/linux-cloud-hypervisor/clear-31890-kvm.img \
    --cmdline "console=hvc0 reboot=k panic=1 nomodules i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd root=/dev/vda3" \
    --cpus boot=1 --memory size=1024M  --api-socket /tmp/api -vv --log-file /tmp/dbg.log &

for i in {1..300}
do
    echo "Wait 4 seconds while guest booting...."
    sleep 4
    echo ""
    echo "Reboot the VM for the [$i] time..."
    /home/chenb/project/cloud-hypervisor/cloud-hypervisor/target/debug/ch-remote --api-socket=/tmp/api reboot
done
```

**Comment by rbradford** [comment]
FYI, "--cmdline" has no effect when using the firmware.

Sadly I can't reproduce this, can you reproduce it consistently? Does it take half as long if you use e.g. 2 vcpus or a quarter with 4?

**Comment by likebreath** [comment]
@rbradford Hmm... Surprised that it can't be reproduced on your side. I can constantly reproduce it on my host machine. Let me try to run it inside a VM and see how that goes. I will keep you posted on that.

No, the number of vcpus makes no difference on iterations to hit the error. I used to run 18 vcpus, and it also took the 235 iterations to hit the error.

**Comment by rbradford** [comment]
So the reason i couldn't reproduce it was that I wasn't using the exact same configuration. Out of habit I always run with `--console off --serial tty` so I can see the boot messages. When I remove those to enable vitio-console I see it failing after 235 runs as you say.

**Comment by sboeuf** [comment]
@likebreath looks like you have something fun you can debug/investigate :)

From some quick investigation on my side, I can see we have some file descriptor leaks. When using `--console off --serial tty`, we leak 3 fds for each reboot, while we leak 4 fds when using `--console tty --serial off`.
This file descriptor leak leads to some issue after either ~315 times or ~233 times because added to the CH offset of 79 (with `--console off --serial tty`) or 95 (when `--console tty --serial off`), we hit the standard open files limit of 1024.

A quick test you can try on your machine to confirm this theory:
- increase the ulimit for the number of open files allowed for each process
```
ulimit -n 2048
```
- Run the test 235 times, it should not fail this time, but it should fail later, around 488 times.

If this is confirmed, then we need to identify places in the code where we leak these file descriptors.

**Comment by likebreath** [comment]
The root cause is located to `epoll::create()`. Various virtio devices used it to allocate fd's (`epoll_fd`) for polling but never close them. I submit a draft PR #1181 trying to fix it. Most of the `epoll_fd` are self-contained to the `EpollHandler::run` function, and can be easily closed before function returns. The only exception is `VsockMuxer`, and I added a `drop` trait to close the `epoll_fd` manually. 

Besides virtio devices, `epoll::create()` is also used in `vmm:EpollContext` and `vhost_user_backend::VringWorker`. They are not causing file descriptor leak practically, as `vmm` thread is a long running thread and `vhost_user` seems to relaunch the whole process every-time with `vm.reboot`.

Any thoughts or suggestions, please let me know. Thanks. @rbradford @sboeuf @sameo

**Comment by sboeuf** [comment]
Thanks for finding the root cause :)
I left some comments on the PR.
