### ISSUE TITLE
https://github.com/cloud-hypervisor/linux need update

### ISSUE THREAD

**Issue by teawater** [cloud-hypervisor/cloud-hypervisor#1320]
virtio-mem is upstreamed.
And virtio_mem_config is updated by https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=544fc7dbbf920a3e64d109c416ee229e8e1763c5.

I post a PR to update VirtioMemConfig to support this update.

Looks https://github.com/cloud-hypervisor/linux need update.

**Comment by sboeuf** [comment]
@teawater thanks for notifying us about it :)
With the upstream kernel, we should be able to get rid of both the `vsock` and `virtio-mem` patches that we've been carrying on for some time.
`virtio-iommu` and `virtio-fs` patches are not updated yet for the latest kernel, that's why we have to wait before we can move to the latest kernel.

**Comment by rbradford** [comment]
Fixed #1449
