### ISSUE TITLE
Support backing guest memory with PMEM

### ISSUE THREAD

**Issue by arronwy** [cloud-hypervisor/cloud-hypervisor#1408]
Intel Optane Persistent Memory can be exported as system ram in the Host side and will be placed in a seperated numa node without cpu attached. We also want cloud hypervisor can support PMEM allocation, in order to let the Guest aware different memory type like DRAM and PMEM, and overcommit for different memory type, we may need assign DRAM and PMEM in Guest to seperate numa node.  Like in qemu, it support create different numa nodes, and memory assigned to different virtio-mem devices will placed in different numa node in Guest by default. We may don't need the same interface but we may need similar implementation to assign Host DRAM/PMEM to Guest and place in different numa node.

```
-m 2G,maxmem=20G \ # "boot + DMA" Memory 
-numa node,nodeid=0,cpus=0-1 -numa node,nodeid=1,cpus=2-3 \
-object memory-backend-ram,id=mem0,size=4G,max-size=8G \ # DRAM memory able to add/remove
-device virtio-mem-pci,id=reg0,memdev=mem0,node=0 \
-object memory-backend-ram,id=mem1,size=2G,max-size=8G \ # PMEM memory able to add/remove
-device virtio-mem-pci,id=reg1,memdev=mem1,node=1
```
The main features required by this issue are:
1. KMEM CGroup support (depends on kernel team)
2. Numa node support in cloud hypervisor
3. Assign DRAM/PMEM to different numa node in Guest by cloud hypervisor

**Comment by rbradford** [comment]
Please work on designing what the Cloud Hypervisor API would look like.

**Comment by Jiangbo-W** [comment]
The Cloud Hypervisor API includes the external API and internal API, currently we will focus on the external API for the user to use DCPMM as memory in Cloud Hypervisor.

Since current kernel cgroup doesn't support allocation/limitation for different memory types. In order to expose different ratio DRAM/PMEM to Guest, we need multiple memory devices to support different memory types.
Current DRAM command line interface API includes allocation and hotplug config, and REST API resize to control the hotplug memory like below:

        --memory  size=<guest_memory_size>,file=<backing_file_path>,mergeable=on|off,hotplug_size=<hotpluggable_memory_size>

       ch-remote --api-socket cloud-hypervisor.sock resize –memory = <size>

To support both DRAM and PMEM, we propose following three API options:
Option1: 
        --memory size=512M,hostplug_method=virtio-mem           \
                hotplug_size=1G,host_nodes="node0",id="vm0"     \
                hotplug_size=1G,host_nodes="node1",id="vm1"     \

**id** is used to distinguish each memory device. **host_nodes** is used to restrict numa node on which memory can be allocated, and **hotplug_size** is used as hotpluggable memory size. In order to plug/unplug memory from Guest, we use virtio-mem as the memory device.
And Resize APIs:
        ch-remote --api-socket cloud-hypervisor.sock resize --memory=1073741824,id="vm0"

ACPI hotplug will be like this:
        --memory size=512M,hotplug_method=acpi                  \
                hotplug_size=1G,host_nodes="node0",id="dimm0"   \
                hotplug_size=1G,host_nodes="node1",id="dimm0"   \

This option will be more generic and depend on users to identify which node is DRAM/PMEM. ex. Kata will do mapping 'DRAM/PMEM <-> Node(n)'. 

Option2:
We can simplify the API interface to reduce dependencies and easy to use.

        --memory size=512M,hostplug_method=virtio-mem           \
                hotplug_size=1G,host_node="dram"                \
                hotplug_size=1G,host_nods="pmem"                \

And Resize APIs:
        ch-remote --api-socket cloud-hypervisor.sock resize --dram=<size>
        ch-remote --api-socket cloud-hypervisor.sock resize --pmem=<size>

Option3:
        --memory size=512M,hotplug_method=virtio-mem            \
                hotplug_dram_size=1G                            \
                hotplug_pmem_size=1G                            \

And Resize APIs is same as Option2.

Any suggestions?

**Comment by Jiangbo-W** [comment]
The Cloud Hypervisor API includes the external API and internal API, currently we will focus on the external API for the user to use DCPMM as memory in Cloud Hypervisor.

Since current kernel cgroup doesn't support allocation/limitation for different memory types. In order to expose different ratio DRAM/PMEM to Guest, we need multiple memory devices to support different memory types.
Current DRAM command line interface API includes allocation and hotplug config, and REST API resize to control the hotplug memory like below:

        --memory  size=<guest_memory_size>,file=<backing_file_path>,mergeable=on|off,hotplug_size=<hotpluggable_memory_size>

       ch-remote --api-socket cloud-hypervisor.sock resize –memory = <size>

To support both DRAM and PMEM, we propose following three API options:
Option1: 
```
        --memory size=512M,hostplug_method=virtio-mem      \
                hotplug_size=1G,host_nodes="node0",id="vm0"     \
                hotplug_size=1G,host_nodes="node1",id="vm1"     \
```

_id_ is used to distinguish each memory device. _host_nodes_ is used to restrict numa node on which memory can be allocated, and _hotplug_size_ is used as hotpluggable memory size. In order to plug/unplug memory from Guest, we use virtio-mem as the memory device.
And Resize APIs:
        ch-remote --api-socket cloud-hypervisor.sock resize --memory=1073741824,id="vm0"

ACPI hotplug will be like this:
```
        --memory size=512M,hotplug_method=acpi                     \
                hotplug_size=1G,host_nodes="node0",id="dimm0"   \
                hotplug_size=1G,host_nodes="node1",id="dimm0"   \
```

This option will be more generic and depend on users to identify which node is DRAM/PMEM. ex. Kata will do mapping 'DRAM/PMEM <-> Node(n)'. 

Option2:
We can simplify the API interface to reduce dependencies and easy to use.

```
        --memory size=512M,hostplug_method=virtio-mem           \
                hotplug_size=1G,host_node="dram"                             \
                hotplug_size=1G,host_nods="pmem"                           \
```

And Resize APIs:
        ch-remote --api-socket cloud-hypervisor.sock resize --dram=<size>
        ch-remote --api-socket cloud-hypervisor.sock resize --pmem=<size>

Option3:
        --memory size=512M,hotplug_method=virtio-mem            \
                hotplug_dram_size=1G                            \
                hotplug_pmem_size=1G                            \

And Resize APIs is same as Option2.

Any suggestions?

**Comment by Jiangbo-W** [comment]
The Cloud Hypervisor API includes the external API and internal API, currently we will focus on the external API for the user to use DCPMM as memory in Cloud Hypervisor.

Since current kernel cgroup doesn't support allocation/limitation for different memory types. In order to expose different ratio DRAM/PMEM to Guest, we need multiple memory devices to support different memory types.
Current DRAM command line interface API includes allocation and hotplug config, and REST API resize to control the hotplug memory like below:

```
        --memory  size=<guest_memory_size>,file=<backing_file_path>,mergeable=on|off,hotplug_size=<hotpluggable_memory_size>

        ch-remote --api-socket cloud-hypervisor.sock resize –memory = <size>
```

To support both DRAM and PMEM, we propose following three API options:
Option1: 
```
        --memory size=512M,hostplug_method=virtio-mem      \
                hotplug_size=1G,host_nodes="node0",id="vm0"     \
                hotplug_size=1G,host_nodes="node1",id="vm1"     \
```

_id_ is used to distinguish each memory device. _host_nodes_ is used to restrict numa node on which memory can be allocated, and _hotplug_size_ is used as hotpluggable memory size. In order to plug/unplug memory from Guest, we use virtio-mem as the memory device.
And Resize APIs:
        `ch-remote --api-socket cloud-hypervisor.sock resize --memory=1073741824,id="vm0"`

ACPI hotplug will be like this:
```
        --memory size=512M,hotplug_method=acpi                     \
                hotplug_size=1G,host_nodes="node0",id="dimm0"   \
                hotplug_size=1G,host_nodes="node1",id="dimm0"   \
```

This option will be more generic and depend on users to identify which node is DRAM/PMEM. ex. Kata will do mapping 'DRAM/PMEM <-> Node(n)'. 

Option2:
We can simplify the API interface to reduce dependencies and easy to use.

```
        --memory size=512M,hostplug_method=virtio-mem           \
                hotplug_size=1G,host_node="dram"                             \
                hotplug_size=1G,host_nods="pmem"                           \
```

And Resize APIs:
```
        ch-remote --api-socket cloud-hypervisor.sock resize --dram=<size>
        ch-remote --api-socket cloud-hypervisor.sock resize --pmem=<size>
```

Option3:
```
        --memory size=512M,hotplug_method=virtio-mem            \
                hotplug_dram_size=1G                            \
                hotplug_pmem_size=1G                            \
```

And Resize APIs is same as Option2.

Any suggestions?

**Comment by Jiangbo-W** [comment]
The Cloud Hypervisor API includes the external API and internal API, currently we will focus on the external API for the user to use DCPMM as memory in Cloud Hypervisor.

Since current kernel cgroup doesn't support allocation/limitation for different memory types. In order to expose different ratio DRAM/PMEM to Guest, we need multiple memory devices to support different memory types.
Current DRAM command line interface API includes allocation and hotplug config, and REST API resize to control the hotplug memory like below:

```
        --memory  size=<guest_memory_size>,file=<backing_file_path>,mergeable=on|off,hotplug_size=<hotpluggable_memory_size>

        ch-remote --api-socket cloud-hypervisor.sock resize –memory = <size>
```

To support both DRAM and PMEM, we propose following three API options:
Option1: 
```
        --memory size=512M,hostplug_method=virtio-mem      \
                hotplug_size=1G,host_nodes="node0",id="vm0"     \
                hotplug_size=1G,host_nodes="node1",id="vm1"     \
```

_id_ is used to distinguish each memory device. _host_nodes_ is used to restrict numa node on which memory can be allocated, and _hotplug_size_ is used as hotpluggable memory size. In order to plug/unplug memory from Guest, we use virtio-mem as the memory device.
And Resize APIs:
`        ch-remote --api-socket cloud-hypervisor.sock resize --memory=<size>,id="vm0"`

ACPI hotplug will be like this:
```
        --memory size=512M,hotplug_method=acpi                     \
                hotplug_size=1G,host_nodes="node0",id="dimm0"   \
                hotplug_size=1G,host_nodes="node1",id="dimm0"   \
```

This option will be more generic and depend on users to identify which node is DRAM/PMEM. ex. Kata will do mapping 'DRAM/PMEM <-> Node(n)'. 

Option2:
We can simplify the API interface to reduce dependencies and easy to use.

```
        --memory size=512M,hostplug_method=virtio-mem           \
                hotplug_size=1G,host_node="dram"                             \
                hotplug_size=1G,host_nods="pmem"                           \
```

And Resize APIs:
```
        ch-remote --api-socket cloud-hypervisor.sock resize --dram=<size>
        ch-remote --api-socket cloud-hypervisor.sock resize --pmem=<size>
```

Option3:
```
        --memory size=512M,hotplug_method=virtio-mem            \
                hotplug_dram_size=1G                            \
                hotplug_pmem_size=1G                            \
```

And Resize APIs is same as Option2.

Any suggestions?

**Comment by Jiangbo-W** [comment]
The Cloud Hypervisor API includes the external API and internal API, currently we will focus on the external API for the user to use DCPMM as memory in Cloud Hypervisor.

Since current kernel cgroup doesn't support allocation/limitation for different memory types. In order to expose different ratio DRAM/PMEM to Guest, we need multiple memory devices to support different memory types.
Current DRAM command line interface API includes allocation and hotplug config, and REST API resize to control the hotplug memory like below:

```
        --memory  size=<guest_memory_size>,file=<backing_file_path>,mergeable=on|off,hotplug_size=<hotpluggable_memory_size>

        ch-remote --api-socket cloud-hypervisor.sock resize –memory = <size>
```

To support both DRAM and PMEM, we propose following three API options:
Option1: 
```
        --memory size=512M,hostplug_method=virtio-mem      \
                hotplug_size=1G,host_nodes="node0",id="vm0"     \
                hotplug_size=1G,host_nodes="node1",id="vm1"     \
```

_id_ is used to distinguish each memory device. _host_nodes_ is used to restrict numa node on which memory can be allocated, and _hotplug_size_ is used as hotpluggable memory size. In order to plug/unplug memory from Guest, we use virtio-mem as the memory device.
And Resize APIs:
```
        ch-remote --api-socket cloud-hypervisor.sock resize --memory=<size>,id="vm0"
```

ACPI hotplug will be like this:
```
        --memory size=512M,hotplug_method=acpi                     \
                hotplug_size=1G,host_nodes="node0",id="dimm0"   \
                hotplug_size=1G,host_nodes="node1",id="dimm0"   \
```

This option will be more generic and depend on users to identify which node is DRAM/PMEM. ex. Kata will do mapping 'DRAM/PMEM <-> Node(n)'. 

Option2:
We can simplify the API interface to reduce dependencies and easy to use.

```
        --memory size=512M,hostplug_method=virtio-mem           \
                hotplug_size=1G,host_node="dram"                             \
                hotplug_size=1G,host_nods="pmem"                           \
```

And Resize APIs:
```
        ch-remote --api-socket cloud-hypervisor.sock resize --dram=<size>
        ch-remote --api-socket cloud-hypervisor.sock resize --pmem=<size>
```

Option3:
```
        --memory size=512M,hotplug_method=virtio-mem            \
                hotplug_dram_size=1G                            \
                hotplug_pmem_size=1G                            \
```

And Resize APIs is same as Option2.

Any suggestions?

**Comment by rbradford** [comment]
I would prefer `--pmem-ram [size=<size>,file=<file>],...` and add a `add-pmem-ram` HTTP endpoint. Under the hood this would add the new memory using ACPI or virtio-mem including NUMA tables.

**Comment by sboeuf** [comment]
@arronwy @Jiangbo-W

After I read about these proposals and after @rbradford and I talked offline about this, here are a few thoughts.

Before going any further, let's not talk about hotplug, as I believe this would just add complexity to the conversation, and before even thinking about hotplugging more DCPMM, let's look at the case where we can boot a VM with both DRAM and DCPMM memory. The hotplug can certainly be added as a second step.

From a CLI perspective, I like the `--pmem-ram` approach as it would not conflict with the existing `--memory` option, which is already quite complex. This would provide a simple way to ask CH for some very "special" RAM. I also expect this would create a better separation inside the CH code.

I have a few questions to clarify what are the expectations for this feature:
1. What do you expect the host system would expose to the user so that we can provide it to Cloud-Hypervisor?
- Either it can be a file like `/dev/pmem0p1`, and in this case, CH would be responsible for opening it and memory map it so that it can be exposed as part of the guest RAM.
- Or it can be part of the system RAM on the host, in which case you __must__ provide the NUMA node associated with it, so that CH could perform the `mbind` correctly.
It's very important to understand how you would refer the backing DCPMM memory to CH, as it will shape the expected parameters and the expected implementation.

2. Do you expect to find all DCPMM memory in the guest to appear through the same NUMA node?

3. At which distance do you expect to find the DCPMM NUMA node? Linux code expects less than 30 I think, otherwise it wouldn't move pages between two NUMA nodes.

4. Do you always expect all vCPUs to be attached to the DRAM NUMA node? 

From an implementation perspective, I did some research and tried to identify what was missing from CH to be able to expose NUMA nodes:
- Expose an SRAT table through ACPI: Add a Memory Affinity structure to describe how a range of memory belongs to a Proximity Domain.
- Expose a SLIT table through ACPI: Create matrix entries for each System Locality (or Proximity Domain) to define how far each node stand from each other and from itself.
- Extend ACPI description of each CPU device: Add a `_PXM` method to identify which Proximity Domain a vCPU relates to.

__Note:__ It's also very important that we don't prevent further extension of CH regarding wider NUMA support while we tackle this DCPMM feature. I think we must ensure that DCPMM will always appear the furthest compared to any other NUMA node we could ask CH to create.

**Comment by Jiangbo-W** [comment]
Thanks @rbradford @sboeuf 

> @arronwy @Jiangbo-W
> 
> After I read about these proposals and after @rbradford and I talked offline about this, here are a few thoughts.
> 
> Before going any further, let's not talk about hotplug, as I believe this would just add complexity to the conversation, and before even thinking about hotplugging more DCPMM, let's look at the case where we can boot a VM with both DRAM and DCPMM memory. The hotplug can certainly be added as a second step.
> 
> From a CLI perspective, I like the `--pmem-ram` approach as it would not conflict with the existing `--memory` option, which is already quite complex. This would provide a simple way to ask CH for some very "special" RAM. I also expect this would create a better separation inside the CH code.
> 
> I have a few questions to clarify what are the expectations for this feature:
> 
> 1. What do you expect the host system would expose to the user so that we can provide it to Cloud-Hypervisor?
> 
> * Either it can be a file like `/dev/pmem0p1`, and in this case, CH would be responsible for opening it and memory map it so that it can be exposed as part of the guest RAM.
> * Or it can be part of the system RAM on the host, in which case you **must** provide the NUMA node associated with it, so that CH could perform the `mbind` correctly.
>   It's very important to understand how you would refer the backing DCPMM memory to CH, as it will shape the expected parameters and the expected implementation.

We would prefer DCPMM memory is exposed as system RAM on the host, Since fs dax is mounted in filesystem, although it bypass page cache. Dev dax will be dynamically splitted `/dev/daxN.M` to many smaller devices for different VMs. fs dex is not efficient, and dev dex is not flexible. We want to reconfigure DCPMM to system-ram using kmem facility, and then use two different virito-mem devices to expose different memory type with different NUMA nodes. and yes, mbind system call would be used to bind mmap region with virtio-mem.

> 
> 2. Do you expect to find all DCPMM memory in the guest to appear through the same NUMA node?

We hope in the Guest DCPMM memory and DRAM can be in separate NUMA node but since CLH had not supported NUMA in guest as you mentioned, at the first stage DCPMM memory and DRAM can be in the same NUMA node in Guest, and performance optimization with [Memory Tiering](https://git.kernel.org/pub/scm/linux/kernel/git/vishal/tiering.git/?h=tiering-0.4) is in host. Next stage when CLH support different NUMA node, we can do performance optimization in Guest with [Memory Tiering](https://git.kernel.org/pub/scm/linux/kernel/git/vishal/tiering.git/?h=tiering-0.4).

> 3. At which distance do you expect to find the DCPMM NUMA node? Linux code expects less than 30 I think, otherwise it wouldn't move pages between two NUMA nodes.

We expect Memory Tiering to do page migration between different NUMA nodes.

> 4. Do you always expect all vCPUs to be attached to the DRAM NUMA node?

Yes, vCPU will be attached to DRAM NUMA node if the Guest supports NUMA node. and there is not CPUs in DCPMM NUMA node.

> 
> From an implementation perspective, I did some research and tried to identify what was missing from CH to be able to expose NUMA nodes:
> 
> * Expose an SRAT table through ACPI: Add a Memory Affinity structure to describe how a range of memory belongs to a Proximity Domain.
> * Expose a SLIT table through ACPI: Create matrix entries for each System Locality (or Proximity Domain) to define how far each node stand from each other and from itself.
> * Extend ACPI description of each CPU device: Add a `_PXM` method to identify which Proximity Domain a vCPU relates to.
> 
> **Note:** It's also very important that we don't prevent further extension of CH regarding wider NUMA support while we tackle this DCPMM feature. I think we must ensure that DCPMM will always appear the furthest compared to any other NUMA node we could ask CH to create.

Yes, ACPI is needed for NUMA node supported in Guest, and now we forced on memory allocation and limitation for Guest.

**Comment by sboeuf** [comment]
@Jiangbo-W 
>We would prefer DCPMM memory is exposed as system RAM on the host, Since fs dax is mounted in filesystem, although it bypass page cache. Dev dax will be dynamically splitted /dev/daxN.M to many smaller devices for different VMs. fs dex is not efficient, and dev dex is not flexible.

Ok.

>We want to reconfigure DCPMM to system-ram using kmem facility, and then use two different virito-mem devices to expose different memory type with different NUMA nodes. and yes, mbind system call would be used to bind mmap region with virtio-mem.

What is the kmem facility doing?

And why do you need 2 `virtio-mem` devices? If hotplug is out of the picture, do you still need `virtio-mem` for some other requirements?

>We hope in the Guest DCPMM memory and DRAM can be in separate NUMA node but since CLH had not supported NUMA in guest as you mentioned, at the first stage DCPMM memory and DRAM can be in the same NUMA node in Guest, and performance optimization with Memory Tiering is in host. Next stage when CLH support different NUMA node, we can do performance optimization in Guest with Memory Tiering.

It sounds like doing the optimization on the host would be quite complex and not as efficient as performing it directly in the guest, is that right?
I think as long as we have a clear view on what we want to implement here, the part about NUMA should be doable, therefore I'm not sure we want to go through an intermediate step with the host optimization you mentioned.

**Comment by Jiangbo-W** [comment]
@rbradford 

> > We want to reconfigure DCPMM to system-ram using kmem facility, and then use two different virito-mem devices to expose different memory type with different NUMA nodes. and yes, mbind system call would be used to bind mmap region with virtio-mem.
> 
> What is the kmem facility doing?
> 

[kmem facility](https://lkml.org/lkml/2020/1/21/1211) allow DCPMM to be added to the system ram.

> And why do you need 2 `virtio-mem` devices? If hotplug is out of the picture, do you still need `virtio-mem` for some other requirements?
> 

If hotplug is out of the picture, we do not need to use `virtio-mem`. But if considering hotplug, both DRAM and DCPMM are all be considered, since they are all the memory in a sense. and hotplug is useful for elastic capacity expansion for CSPs.

> > We hope in the Guest DCPMM memory and DRAM can be in separate NUMA node but since CLH had not supported NUMA in guest as you mentioned, at the first stage DCPMM memory and DRAM can be in the same NUMA node in Guest, and performance optimization with Memory Tiering is in host. Next stage when CLH support different NUMA node, we can do performance optimization in Guest with Memory Tiering.
> 
> It sounds like doing the optimization on the host would be quite complex and not as efficient as performing it directly in the guest, is that right?

Yes, i also think so, but we have no data about which one is good. Fortunately, in theory optimization (refer to Memory Tiering) can be done in both (host or guest), and they are on the way to upstream.

> I think as long as we have a clear view on what we want to implement here, the part about NUMA should be doable, therefore I'm not sure we want to go through an intermediate step with the host optimization you mentioned.

Actually, now we only expect to expose DRAM and DCPMM to Guest using `virito-mem' or other methods, and those different type memory will be no differentiation in guest viewpoint since CLH doesn't support multiple NUMA nodes. And guest multiple NUMA nodes don't affect memory exposing. :)

Optimization in host or guest are fine, and this is another topic. Memory Tiering depends on multiple NUMA nodes. Host has supported multiple NUMA nodes, so Memory Tiering can be done naturally. And CLH doesn't support multiple NUMA nodes now. we can move optimization into guest after CLH support multiple NUMA ndoes. :)

**Comment by rbradford** [comment]
Here is my proposal. I have discussed it with @sboeuf and he has helped to clarify some of the details:

`--memory` is mostly unchanged and is there to support the simple guest cases

Power uses now have access to a `--backed-memory` option that can be used to specify exactly how parts of memory are backed. This is also exposed through the following struct:

```
struct BackedMemoryConfig {
	guest_numa: Option<u64>
	host_numa: Option<u64e>
	guest_numa_distance: Option<u64>
	file: Option<Path>
	size: Option<u64>
	shared: Option<bool>
	hugepages: Option<bool>
}
```

This struct will be expose in the JSON config as a `backed_memory: []` and will be able to add new memory via a HTTP API that consumes this struct. When adding new memory the guest will be notified with whatever `hotplug_method` is already specified/

For cases where the user wants full control of the guest memory they can do `--memory size=0` and will be expected to provide sum number of `--backed-memory` options.

Here are some specific worked examples:

This allocates anonymous shared huge page memory for the guest and is equivalent for what you can do with the existing `--memory`:

```
--memory size=0 --backed-memory size=1G,shared=on,hugepages=on
```

This exists so you can use it to assign across different NUMA nodes (i.e. allocate guest memory from different NUMA nodes and expose that as different guest NUMA nodes.):

```
--memory size=0 --backed-memory size=1G,shared=on,hugepages=on,host_numa_node=1,guest_numa_node=1 size=1G,shared=on,hugepages=on,host_numa_node=1,guest_numa_node=1
```

You could also use this to back the entire guest memory from a file (such as pmem) to facilitate host upgrades without restarting the guest:

```
--memory size=0 --backed-memory=1G,shared=on,hugepages=on,file=/dev/pmem0p1
```

With the power user options there is possibility of specifying a configuration that might break

e.g.

```
--memory size=1G,shared=on --backed-memory=1G,shared=off
```

This would break if the user tried to use vhost-user. However that is the acceptable risk as this is a power user feature.

**Comment by rbradford** [comment]
When `--backend-memory` is added we will remove the `file=` option from `--memory`.

**Comment by Jiangbo-W** [comment]
Just update here, i found vhost_user `MUST` use `MAP_SHARED` flag to mmap region between master (CLH/Qemu) and slave (virtiofsd), this is hard limitation. 

So if enabled virtiofsd, all hot-add mem MUST use this flag to provide memory, otherwise virtiofsd do not remap the region, it will panic if page allocated in the hot-add mem.

But `man mbind` says that: `The specified policy will be ignored for any MAP_SHARED mappings in the specified memory range.`

**Comment by sboeuf** [comment]
@Jiangbo-W that's why when using DCPMM, we couldn't use vhost-user at all. One way to mitigate this problem would be to implement virtio-fs inside the CH device model directly.

**Comment by sameo** [comment]
> Here is my proposal. I have discussed it with @sboeuf and he has helped to clarify some of the details:
> 
> `--memory` is mostly unchanged and is there to support the simple guest cases
> 
> Power users now have access to a `--backed-memory` option that can be used to specify exactly how parts of memory are backed. 

Compared to adding the `guest_numa: Option<u64>` and `host_numa: Option<u64>` fields to the existing `MemoryConfig` structure, and allowing for multiple of them to be defined through `--memory`, what would `BackedMemoryConfig` bring?

> This is also exposed through the following struct:
> 
> ```rust
> struct BackedMemoryConfig {
> 	guest_numa: Option<u64>
> 	host_numa: Option<u64e>
> 	guest_numa_distance: Option<u64>
> 	file: Option<Path>
> 	size: Option<u64>
> 	shared: Option<bool>
> 	hugepages: Option<bool>
> }
> ```

Unless the proposal also implicitly includes defining the memory NUMA topology, I don't think we should have a `guest_numa_distance` field in there because:

1. It might not be the best place to define a NUMA topology
1. A NUMA node distance to its neighbors can only be defined as an array

> This struct will be expose in the JSON config as a `backed_memory: []` and will be able to add new memory via a HTTP API that consumes this struct. When adding new memory the guest will be notified with whatever `hotplug_method` is already specified.
> 
> For cases where the user wants full control of the guest memory they can do `--memory size=0` and will be expected to provide sum number of `--backed-memory` options.
> 
> Here are some specific worked examples:
> 
> This allocates anonymous shared huge page memory for the guest and is equivalent for what you can do with the existing `--memory`:
> 
> ```
> --memory size=0 --backed-memory size=1G,shared=on,hugepages=on
> ```
> 
> This exists so you can use it to assign across different NUMA nodes (i.e. allocate guest memory from different NUMA nodes and expose that as different guest NUMA nodes.):
> 
> ```
> --memory size=0 --backed-memory size=1G,shared=on,hugepages=on,host_numa_node=1,guest_numa_node=1 size=1G,shared=on,hugepages=on,host_numa_node=1,guest_numa_node=1
> ```

I assume you meant `size=1G,shared=on,hugepages=on,host_numa_node=0,guest_numa_node=0` for the second one?

> You could also use this to back the entire guest memory from a file (such as pmem) to facilitate host upgrades without restarting the guest:
> 
> ```
> --memory size=0 --backed-memory=1G,shared=on,hugepages=on,file=/dev/pmem0p1
> ```
> 
> With the power user options there is possibility of specifying a configuration that might break
> 
> e.g.
> 
> ```
> --memory size=1G,shared=on --backed-memory=1G,shared=off
> ```

So does that describe a 1G guest shared memory backed by 1G of **unshared** memory?

**Comment by rbradford** [comment]
> > Here is my proposal. I have discussed it with @sboeuf and he has helped to clarify some of the details:
> > `--memory` is mostly unchanged and is there to support the simple guest cases
> > Power users now have access to a `--backed-memory` option that can be used to specify exactly how parts of memory are backed.
> 
> Compared to adding the `guest_numa: Option<u64>` and `host_numa: Option<u64>` fields to the existing `MemoryConfig` structure, and allowing for multiple of them to be defined through `--memory`, what would `BackedMemoryConfig` bring?
> 

`--memory` and `MemoryConfig` hold details for global memory allocation (such as a the size of the memory vs device split aka `hotplug_size`, the `hotplug_method`.) The allocated memory is also something that could be resizable. Keeping it simple like this means that we can keep handling the the majority of use cases with no change and we don't need to worry about people trying to add multiple `--memory` with conflicting options.

> > This is also exposed through the following struct:
> > ```rust
> > struct BackedMemoryConfig {
> > 	guest_numa: Option<u64>
> > 	host_numa: Option<u64e>
> > 	guest_numa_distance: Option<u64>
> > 	file: Option<Path>
> > 	size: Option<u64>
> > 	shared: Option<bool>
> > 	hugepages: Option<bool>
> > }
> > ```
> 
> Unless the proposal also implicitly includes defining the memory NUMA topology, I don't think we should have a `guest_numa_distance` field in there because:
> 
>     1. It might not be the best place to define a NUMA topology
> 
>     2. A NUMA node distance to its neighbors can only be defined as an array
> 

Okay. We can always add it later but I expect that the best place to define the NUMA topology is across both `--cpus` and `--backed-memory`

> 
> > This struct will be expose in the JSON config as a `backed_memory: []` and will be able to add new memory via a HTTP API that consumes this struct. When adding new memory the guest will be notified with whatever `hotplug_method` is already specified.
> > For cases where the user wants full control of the guest memory they can do `--memory size=0` and will be expected to provide sum number of `--backed-memory` options.
> > Here are some specific worked examples:
> > This allocates anonymous shared huge page memory for the guest and is equivalent for what you can do with the existing `--memory`:
> > ```
> > --memory size=0 --backed-memory size=1G,shared=on,hugepages=on
> > ```
> > 
> > 
> > This exists so you can use it to assign across different NUMA nodes (i.e. allocate guest memory from different NUMA nodes and expose that as different guest NUMA nodes.):
> > ```
> > --memory size=0 --backed-memory size=1G,shared=on,hugepages=on,host_numa_node=1,guest_numa_node=1 size=1G,shared=on,hugepages=on,host_numa_node=1,guest_numa_node=1
> > ```
> 
> I assume you meant `size=1G,shared=on,hugepages=on,host_numa_node=0,guest_numa_node=0` for the second one?

Urgh, yes, or some other number != 1.

> > You could also use this to back the entire guest memory from a file (such as pmem) to facilitate host upgrades without restarting the guest:
> > ```
> > --memory size=0 --backed-memory=1G,shared=on,hugepages=on,file=/dev/pmem0p1
> > ```
> > 
> > 
> > With the power user options there is possibility of specifying a configuration that might break
> > e.g.
> > ```
> > --memory size=1G,shared=on --backed-memory=1G,shared=off
> > ```
> 
> So does that describe a 1G guest shared memory backed by 1G of **unshared** memory?

No it's a guest with 2GiB of RAM the first 1GiB of which is shared and the second is not. This is something you wouldn't want to do as it would probably explode but it's to demonstrate that this is a power user API with the safety rails taken off. :-)

**Comment by sboeuf** [comment]
@arronwy @Jiangbo-W with the recent merge of #1694 I believe the support for DCPMM with Cloud-Hypervisor is now complete. Could you please give this a try and confirm there's nothing left to do. If that's the case, feel free to close this issue :)

**Comment by rbradford** [comment]
I think we should close this and reopen (or open new ones) if there are issues or gaps.

**Comment by arronwy** [comment]
> @arronwy @Jiangbo-W with the recent merge of #1694 I believe the support for DCPMM with Cloud-Hypervisor is now complete. Could you please give this a try and confirm there's nothing left to do. If that's the case, feel free to close this issue :)

Thanks @sboeuf , we have tried with your latest commits and verified this feature works well, we can close this issue now.
