### ISSUE TITLE
ARM64 integration tests build the kernel every time

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1444]
@michael2012z @MrXinWang Can you look at this in order to streamline the build time. Looks like by idea of checking the time doesn't seem to work right.

**Comment by MrXinWang** [comment]
Hi @rbradford ! On my local machine the script behaves well as expected, i.e. the kernel is only built if the config file is newer. 

I tried to `su jenkins` in the CI machine and went to the home directory where the `workloads` dir is there. The problem is caused by the `git clone` initiated by Jenkins everytime we start the CI...The mtime of config file is always the time that CI starts, which means the config file will be always newer than the `Image` in `workloads` dir. Therefore the kernel is built everytime...

**Comment by MrXinWang** [comment]
One method that came into my mind is trying to find the difference between kernel config file in current PR and last PR. As in the CI machine the source code directories are listed in this way:

```
cloud-hypervisor_master       cloud-hypervisor_PR-1435@tmp  cloud-hypervisor_PR-1440      cloud-hypervisor_PR-1443@tmp  cloud-hypervisor_PR-1448
cloud-hypervisor_master@tmp   cloud-hypervisor_PR-1436      cloud-hypervisor_PR-1440@tmp  cloud-hypervisor_PR-1445      cloud-hypervisor_PR-1448@tmp
cloud-hypervisor_PR-1397      cloud-hypervisor_PR-1436@tmp  cloud-hypervisor_PR-1441      cloud-hypervisor_PR-1445@tmp  cloud-hypervisor_PR-1449
cloud-hypervisor_PR-1397@tmp  cloud-hypervisor_PR-1437      cloud-hypervisor_PR-1441@tmp  cloud-hypervisor_PR-1446      cloud-hypervisor_PR-1449@tmp
cloud-hypervisor_PR-1433      cloud-hypervisor_PR-1437@tmp  cloud-hypervisor_PR-1442      cloud-hypervisor_PR-1446@tmp  workspaces.txt
cloud-hypervisor_PR-1433@tmp  cloud-hypervisor_PR-1438      cloud-hypervisor_PR-1442@tmp  cloud-hypervisor_PR-1447
cloud-hypervisor_PR-1435      cloud-hypervisor_PR-1438@tmp  cloud-hypervisor_PR-1443      cloud-hypervisor_PR-1447@tmp
```

@rbradford what do you think?

**Comment by rbradford** [comment]
I would solve this by keeping the Linux kernel source tree around. If not found in ~/workloads, `git clone` else `git fetch && git checkout -f `.

Copy config file in and then compile.

Unless the kernel tree or the kernel config has changed then the kernel compile will be very quick.
