### ISSUE TITLE
Hotplug support for memory zones

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#1664]
Now that Cloud-Hypervisor can handle specific memory zones, we need to introduce the hot-plug/hot-unplug support to them.
We must define and discuss the way we see this feature being supported and make sure we don't miss some corner cases.

**Comment by sboeuf** [comment]
Relates to #1408

**Comment by sboeuf** [comment]
I've started thinking about this a bit more and I'm looking for feedback. @rbradford @sameo @arronwy @Jiangbo-W

A quick note this analysis is based on what's doable with `virtio-mem`, since ACPI hotplug is a simpler subset (since the unplug is not supported at all).

First, we can look at hotplug/unplug from 2 point of view. Either we can `resize` or we can `add`/`remove`.
- In case of `resize` we allow the user for a very fine grained control as we allow for removing less than the amount previously added (ex: remove 128M after we added 1G).
- In case of `add`/`remove`, things are easier and more straightforward for the VMM as it expects the user to add a brand new zone or remove it completely. But this gives less control to the user.

Based on these observations, we have two choices:
- Either we create a hotplug region (one `virtio-mem` device) per memory zone, which means we would `resize` each zone independently, hence more control. This operation would fail in case the memory zone would be backed by a regular file as there's no way for the VMM to expand or shrink the region. This would require the `hotplug_size` and `hotplug_method` to be specified at the `--memory-zone` level instead of `--memory` level.
- Or we `add`/`remove` entire memory zones (all backed by the same `virtio-mem` device). The user would be forced to add one or more regions depending on the potential need for removing these regions later. If the hotplugged region is 16G and the user might want to remove 4G later on, depending on the usage from the guest, that means we should anticipate by hotplugging 4G memory zones, so that we could remove them entirely.

A third solution could be the combination of these two proposals, as it would allow new memory zones to be hotplugged, but let the chance for a fine grained unplug if needed.

My take on this so far is that we should keep things simple, therefore go with the `add`/`remove` solution first. We could still attempt to combine with the `resize` solution at some point. And from a use case perspective, even if it's a little bit more tedious, one could still hotplug/unplug new types and size of memory to a running VM.

@arronwy @Jiangbo-W in the context of the DCPMM use case that we discussed on #1408, do you think the proposal of adding/removing entire memory zones would give you the flexibility you're looking for?

**Comment by rbradford** [comment]
The add/remove case is definitely the best. If you wanted to handle reducing by less just add the delta as a new one and remove the original.

**Comment by Jiangbo-W** [comment]
IMHO, i like `resize` a little more as memory zones of divide and rule maybe have more power.

Based on `virtio-mem`, there are no guarantees on how much memory can get unplugged. So if end user remove 4G for entire memory zone, maybe portion range in memory zone is removed in virtio-mem driver. and cloud-hypervisor should still keep monitoring and manage the remained range for the removing memory zone so that they can be removed if all pages are migrate to other zones, i think it's also not easy unless we ignore them. Another concern is that end user need to know which are in-use, which are free so that they can remove entire memory-zone.

Anyway, it's only my personal thinking, correct me if i'm wrong.

**Comment by sameo** [comment]
I think `add/remove` and `resize` would have different semantics, although they do overlap. AFAIU with `resize` you can conveniently change the size of an existing, NUMA mapped memory zone. `add/remove` covers more actions since you could e.g. add new memory zones mappiing an unmapped host NUMA node to an already mapped guest one.

I think we may eventually need both, but I believe it would be simpler to start with `resize` for resizing an existing memory zone. Yes, as @rbradford pointed out, `resize` could be functionally implemented through an `add` and a `remove` but the user should also be careful about using the same NUMA mappings for really doing the equivalent of a `resize`.
