### ISSUE TITLE
Make --kernel option optional like qemu if the image has the kernel in it. 

### ISSUE THREAD

**Issue by russell-islam** [cloud-hypervisor/cloud-hypervisor#1703]
Right now, the --kernel option is mandatory if I am not wrong. Creating this issue to track and discuss on --kernel option making optional. Feel free to fill the gaps.

**Comment by russell-islam** [comment]
Typically we should be able to bring a VM image and able to boot without kernel option.

**Comment by sboeuf** [comment]
The point in having `kernel` mandatory is because even when we boot the image from the kernel it contains, we use the `--kernel` to provide the firmware that will access the EFI partition.
Now, that being said, we could have a dedicated `--fw` option for that.

**Comment by russell-islam** [comment]
That would be better as it will clarify some confusions around --kernel option.

**Comment by rbradford** [comment]
We don't need a dedicated `--fw` option as we use the same loading method for Linux kernel (ELF with PVH header) as for our firmware implementations. QEMU has a default value for their `--bios` option because it is compiled in to point to a Seabios installed.

As a design choice we don't ship with any expectation for the user having a firmware installed in particular location. As such it is always necessary to provide a path to start the execution of the VM, this could be firmware or a Linux kernel. Our `--kernel` is not comparable to QEMU's.

**Comment by rbradford** [comment]
I opened an issue to handle the documentation gap in the help. #1712
