### ISSUE TITLE
MSIX related hotplug/unplug issue

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#1797]
Observed with Windows (need to try reproduce with Linux)

```
rob@artemis:~/src/cloud-hypervisor (master)$ target/debug/ch-remote --api-socket=/tmp/api add-net tap=
{"id":"_net2","bdf":"0000:00:04.0"}
rob@artemis:~/src/cloud-hypervisor (master)$ target/debug/ch-remote --api-socket=/tmp/api remove-device _net2
rob@artemis:~/src/cloud-hypervisor (master)$ target/debug/ch-remote --api-socket=/tmp/api add-net tap=
{"id":"_net3","bdf":"0000:00:05.0"}
```

```
thread 'vcpu0' panicked at 'index out of bounds: the len is 4 but the index is 256', pci/src/msix.rs:217:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by sboeuf** [comment]
I started investigating this issue. I could reproduce on Linux with a different error message, but the bottom line is, adding then removing then readding a device is broken. This seems to be caused by the fact that the device is not removed from the IO and/or MMIO buses, which leads to the new insertion to fail.
After a git bisect, here is the guilty commit:
```
d793cc4da365ef960a239ff32589efc2635072bd is the first bad commit
commit d793cc4da365ef960a239ff32589efc2635072bd
Author: Rob Bradford <robert.bradford@intel.com>
Date:   Thu Sep 10 09:57:53 2020 +0100

    vmm: device_manager: Extract common PCI code
    
    Extract common code for adding devices to the PCI bus into its own
    function from the VFIO and VIRTIO code paths.
    
    Signed-off-by: Rob Bradford <robert.bradford@intel.com>

 vmm/src/device_manager.rs | 129 +++++++++++++++++++++++-----------------------
 1 file changed, 65 insertions(+), 64 deletions(-)
```

**Comment by sboeuf** [comment]
I've looked at this one, but the behavior is really weird. I've replaced `debug!()` statements with `println!()` ones in the `pci/src/msix.rs` file so that I would get MSI-X related logs only.
I can see MSI-X vectors being setup for the `virtio-blk` and `virtio-net` devices during boot. Problem is, once the VM is fully up and running, adding the new `virtio-net` device does not trigger any MSI-X logs. And when removing, still nothing. And when adding `virtio-net` again, that's where we get `thread 'vcpu0' panicked at 'index out of bounds: the len is 4 but the index is 256', pci/src/msix.rs:217:28`.

This is very weird behavior here, as I don't expect either Windows or the driver to write at the index 256 when the MSI-X `table_entries` length is only 4.

I'd suggest we should wait for https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1798 to be fixed before we dig any further with this issue. Once we can be sure hotplugging a `virtio-net` device works, then we'll reassess if the current issue still occurs.
