### ISSUE TITLE
add support for device throttling

### ISSUE THREAD

**Issue by egernst** [cloud-hypervisor/cloud-hypervisor#1853]
As a user, I need to be able to throttle device IO for guests that leverage Cloud Hypervisor.  

ie, something similar to what you can do with other VMMs:
  * QEMU: https://github.com/qemu/qemu/blob/master/block/throttle-groups.c
  * Firecracker with rate-limiter: https://github.com/firecracker-microvm/firecracker/blob/009ec859fe88f2f44b947775656bce0adbb5cc2c/tests/integration_tests/functional/test_rate_limiter.py

Is this something that is on roadmap for Cloud Hypervisor's device crate?

**Comment by iggy** [comment]
Throttle which devices? Using what metric? IOPS on a disk? Packets on a NIC? Strict limits? Fairness based? 

I like the idea. I just think it needs to be a little better specified or you end up with 3 different ways of doing effectively the same thing (like Qemu ended up with).

**Comment by sboeuf** [comment]
@egernst is there a strong reason why you would need this throttling to be performed by the VMM?
I'm asking because if it can be handled from the outside of the VMM, by constraining process and threads, that would be less intrusive, hence easier.
Now, if what you're looking for can't be done from the outside, that is definitely something we can put in our roadmap.
Also, I agree with @iggy that we need clear goals on what you expect and for which devices you need this.

**Comment by sboeuf** [comment]
We already have 2 issues opened about this:
- https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1285
- https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1286

**Comment by sboeuf** [comment]
@egernst 
>Let me take a look @ what is done via rate-limiting today in Firecracker. Agreed we want a well thought-out UX for this.

Oh yeah that'd be great if you could come up with a proposal for this, then we could take care of the implementation :)

**Comment by sboeuf** [comment]
@egernst 
>doing it 'correctly' with cgroups is a challenge.

What is the hard part? Is it related to finding the threads corresponding to the right virtio device?
