### ISSUE TITLE
virtio thread creation could be handled by vmm instead of vcpu0

### ISSUE THREAD

**Issue by vineethrp** [cloud-hypervisor/cloud-hypervisor#1863]
While working on cpupin support for libvirt CH driver, I noticed that vcpu0 creates virtio_blk, virtio_rng etc. libvirt driver implements cpu pinning by moving vcpu threads to its own cpuset cgroup. CPU throttling is also done the same way(cpu cgroup). A side effect of the virtio* thread creation by vcpu0 is that, the vcpu0 cgroup now pulls in the virtio threads as well and hence the pinning, throttling etc gets applied to virtio thread as well.

It would be nice to have vmm thread handle all the thread creation. That way, it becomes straight forward to use cgroups for vcpu threads.

**Comment by sboeuf** [comment]
This comes from the fact that virtio device activation (which happens when the virtio driver write DRIVER_READY) results from a VM exit based on an MMIO write.
We could find a way to defer VM exit handling to the `vmm` thread, but two questions come to mind:
- Would it cause a bottleneck, decreasing the performance?
- Is there any way to filter what should vs shouldn't be deferred?

/cc @sameo

**Comment by sboeuf** [comment]
>I think starting the virtio threads from the vmm thread would be nice but I don't think it would be easy.

I think so as well, but it'd be good to discuss potential designs to tackle this issue.

**Comment by rbradford** [comment]
Options:

1. forward all MMIO writes (and maybe reads for consistency) to the VMM thread (or a dedicated thread derived from the VMM thread) over a channel. If we did the same with PIO too we could remove the CPU threads having any references to the mmio/pio busses.

2. Give every virtio device some way to reference the VMM API receiver and post a request (perhaps a closure?) to ask it start the thread. (Lots of code, very intrusive.)

3. Register an ioeventfd for all mmio addresses (or possibly just those added to the bus). Poll on that ioeventd in the VMM thread (as part of `control_loop()`) or in a (new) VM thread. Walk the mmio bus in that thread rather than the vCPU one.

Option 3. is my favourite as we already do ioeventfd for mmio control of virtio-pci registers. I think I would prefer it in a new VM thread so that we don't fill up the VMM thead (and have to tell it about the buses.)

**Comment by rbradford** [comment]
For more on option 3 - we would just need to have an ioeventfd registered for the specific config address register containing the status bit.

**Comment by rbradford** [comment]
@vineethrp Please check to see if #1953 addresses the problem

**Comment by rbradford** [comment]
Option 4, the one I implemented in #1953 was to signal to the VMM thread via an EventFd that a virtio device might need activation and have the VMM thread via device manager activate all pending virtio devices.

However i've been reading some more about cgroups / posix threads:

1. There is no thread hierarchy with posix threads, they're all parented on the main process irrespective what created them
2. cgroups supports assigning threads to different groups either via cgroups1 or with cgroups2 via the "thread mode". I think that the true fix for this issue should be at the libvirt level to create the correct cgroup structure and assign the threads.

**Comment by vineethrp** [comment]
> @vineethrp Please check to see if #1953 addresses the problem

@rbradford , thanks for implementing this feature. I confirm that the cpu pinnings are showing correctly with this fix for #1953

**Comment by rbradford** [comment]
There is a problem with this design in #1953 and that is that the MMIO write for enabling the device returns immediately even if the device is not yet activated. This is showing up as errors initialising the virtio net device on the CI.

We can't wait for the activation as part of the MMIO writing code as that results in deadlock between the vcpu thread and the vmm thread (mutex held for MMIO write in CPU thread and mutex held for device from VMM thread in device manager.)

Again the synchronous requirement for device activation also precludes using an `ioeventfd` tied to the MMIO status register being used (option 3.)

This leaves the only viable option being option 1 with a synchronous transfer of MMIO write requests to the VMM thread. I think this will really harm performance.

If we do #1862 would that make it easier to solve your underlying problem without having to move the thread creation?

**Comment by vineethrp** [comment]
The main problem is, virtio threads gets created like 3-4 seconds after vcpu thread is created. So when we call the API after a VM creation, most probably virtio threads would not be populated in the response.

If #1953 is not feasible and if its not possible to have a clean solution to this, the option we have in libvirt driver is as follows:
1. Assign vcpu0 to vcpu0 cgroup as we do now.
2. Create inotify watch on /proc/<pid>/tasks folder. Whenever a new create happens on the folder, parse the directory, get the new thread pid and assign it to the emulator cgroup immediately.

This is doable, but a bit involved I think. Will need to try it out and see the details and other implications..

**Comment by sameo** [comment]
Another option would be to create the virtio threads at device creation time, and synchronously pause them (activate and pause). When the device manager is done creating a virtio device, we'd have the guarantee that all its threads are paused. Since the VMM thread creates the device through the device manager, it would also be creating its threads.

Then, when we get an actual activation request from the driver, we'd wake up the threads from the MMIO exit handler (`write_bar`). That can also be done synchronously without potential deadlocks by e.g. waiting for all device threads to check in before returning from `write_bar`.

The drawback here is the potential resource waste as some device may not get to be activated. We'd waste a few fds and some kernel memory overhead, but no CPU cycles.

Am I missing something? Is there something that we'd be missing at creation time that would prevent us from creating the threads ahead of activation? Number of threads to be created maybe?

**Comment by rbradford** [comment]
The number of threads is determined by the guest (i.e. virtio-net MQ or virtio-block MQ). We only know this at activation time.

**Comment by rbradford** [comment]
>     2. Create inotify watch on /proc//tasks folder. Whenever a new create happens on the folder, parse the directory, get the new thread pid and assign it to the emulator cgroup immediately.
> 
> 
> This is doable, but a bit involved I think. Will need to try it out and see the details and other implications..

You're going to need to do this anyway to handle device hotplug and cpu hotplug.
