### ISSUE TITLE
test_windows_guest_snapshot_restore fails

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2126]
This test is quite consistently failing on the CI.

**Comment by sboeuf** [comment]
@rbradford could you point to the jenkins logs related to these failures?
Also, are you sure the windows image hasn't been corrupted in some way, making the test consistently failing? Since you removed the part in the Jenkinsfile downloading a brand new image each time, we might have a corrupted image that causes these failures.

**Comment by rbradford** [comment]
@sboeuf The test never finishes (gets killed by timeout). The image is copied afresh from workload directory for every test so I don't think we're getting a corrupted image. Further `test_windows_guest` passes fine.
