### ISSUE TITLE
PTY is unusable after rebooting the VM

### ISSUE THREAD

**Issue by devimc** [cloud-hypervisor/cloud-hypervisor#2316]
How to reproduce it?

**Terminal 1**

```bash
$ curl -LOk https://cloud-images.ubuntu.com/groovy/current/groovy-server-cloudimg-amd64.img 
$ qemu-img convert -p -f qcow2 -O raw groovy-server-cloudimg-amd64.img groovy-server-cloudimg-amd64.raw
$ ./cloud-hypervisor \
  --kernel ./OVMF.fd \
  --disk path=groovy-server-cloudimg-amd64.raw \
  --cpus boot=4 \
  --memory size=1024M \
  --net "tap=,mac=,ip=,mask=" \
  --rng \
  --api-socket api.sock \
  --console pty
```

**Terminal 2**

```bash
$ screen -O -m $(./ch-remote --api-socket api.sock info  | grep -o "/dev/pts/[[:digit:]]")
ubuntu login: root
Password: 
Welcome to Ubuntu 20.10 (GNU/Linux 5.8.0-43-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Feb 26 16:51:01 UTC 2021

  System load: 0.0               Memory usage: 17%   Processes:       124
  Usage of /:  64.0% of 1.96GB   Swap usage:   0%    Users logged in: 0


0 updates can be installed immediately.
0 of these updates are security updates.


The list of available updates is more than a week old.
To check for new updates run: sudo apt update
Failed to connect to https://changelogs.ubuntu.com/meta-release. Check your Internet connection or proxy settings


Last login: Fri Feb 26 16:40:58 UTC 2021 on hvc0
root@ubuntu:~# reboot 

# Run screen once more
$ screen -O -m $(./ch-remote --api-socket api.sock info  | grep -o "/dev/pts/[[:digit:]]")
```
**After rebooting the VM, the PTY is unusable, input/output are not handled correctly**

**Comment by bryteise** [comment]
Hrm I guess the PTY should be setup outside the VM in that case then. @sboeuf or @rbradford any thoughts on where the data should live?

**Comment by rbradford** [comment]
I think you need to rethink the way the PTY is used as when we reboot we tear the whole VM down and construct it anew (with a potentially different configuration). From my quick reading of the code I think you need to move to a model where CH doesn't create the pty pair - because when we destroy the VM as part of the reboot we trigger the close of the FD. What about moving to a situation where the layer above provides the PTY master fd to CH and it then it uses it, that should be resilient to reboot.

(And no we can't change the way we reboot, we tried that (and failed) in the past when we were a lot less complicated that we are now....)

**Comment by rbradford** [comment]
This would also mean you don't need the hack where you patch the serial file of the config to contain the other end of the PTY pair as that would be done by the layer above.
