### ISSUE TITLE
Implement vTPM support

### ISSUE THREAD

**Issue by russell-islam** [cloud-hypervisor/cloud-hypervisor#2343]
This issue is to discuss the viability of implementing vTPM support in Cloud Hypervisor.

**Comment by gbalane** [comment]
We need vTPM support for cloud/edge usecases.  
QEMU already provides the support for this. 
Also, there is swtpm library https://github.com/stefanberger/swtpm/wiki that supports this as well as emulated device. 
CrosVM did some virtio based TPM here: 
https://chromium.googlesource.com/chromiumos/platform/crosvm/+/18ce5713e6cb99c40aafec52b67c28ba12a44f31/devices/src/virtio/tpm.rs

We need to develop a plan to support this.

**Comment by sameo** [comment]
I think there are 2 aspects to cover here:

1. How do we expose a TPM into the guest
2. Which backend(s) do we want to support

For 1, I definitely prefer the virtio approach against a register emulation of a TIS device. That brings guest dependencies that are not upstreamed (virtio-tpm does not exist) but keeps the VMM side much simpler. We already have a similar situation with virtio watchdog and if we can assume enlightened guest, then I believe this is a better solution.

For 2, this is more complex as things can range from simple libtpm based emulators to TEE (e.g. SGX) build TPMs for scaling across. I dont think using the actual host TPM scales across different VMs.
In our case, we could provide a generic enough TPM backend trait to be flexible and provide different backend depending on the actual needs, but I think starting with a simple filesystem based emulator would be a good first step.

In any case, we first need to agree with going with a virtio based emulated TPM, and have it talk to anything that'd implement a `TPMBackend` trait.  @rbradford @sboeuf WDYT?

**Comment by rbradford** [comment]
We could expose the virtio-tpm as a socket so that you can plug whatever implementation you want in: simulator or a version that makes use of the hardware.

**Comment by sameo** [comment]
> We could expose the virtio-tpm as a socket so that you can plug whatever implementation you want in: simulator or a version that makes use of the hardware.

vhost-user-tpm :-)

**Comment by sboeuf** [comment]
I'm in favor of using `virtio` as the way to expose a vTPM to the guest. Since it's already there for `crosvm`, we could simply pull their virtio driver into our guest kernel. And in terms of PoC, this is the quickest solution as we can rely mostly on the code from `crosvm`.

We might still choose the emulation approach eventually, as this would avoid the guest enlightenment, meaning more users might benefit from it.

About the backend, I'm not a huge fan of using vhost-user in anticipation for potential users with different needs. We should pick what we think is best and stick to our choice. If using the host TPM is not scalable, then we should not consider this as a valid approach.
Again, using the crosvm approach might be the most straightforward solution, and it might fit both our expectations for frontend and backend.

**Comment by rbradford** [comment]
I think advertising it as virtio-tpm to the guest is nice (and there is a driver we can find from Google to do that) but on the host side the implementation needs to be in pure Rust (or abstracted across a socket.) Trying to bring in non-Rust code has been a huge pain point in the past: e.g. libfdt such to the extent that we're trying to remove it (by switching to ACPI).

**Comment by liuw** [comment]
One thing to consider is Windows support. I don't think there is a virtio-tpm frontend driver for Windows yet.

**Comment by sameo** [comment]
Windows support also potentially includes bootloader support, where the hypothetical windows kernel virtio TPM driver would not be present.

**Comment by liuw** [comment]
We can run https://github.com/stefanberger/swtpm behind a socket and let CLH forward commands to it.

CLH handle TPM's registers and memory regions and forward stuff to the socket.

**Comment by sboeuf** [comment]
This could directly benefit from the approach proposed [here](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/2594) of using `vfio-user`.

**Comment by sboeuf** [comment]
@rbradford 
Just a note that TPM drivers expect a TPM device to be located on an i2c bus and not a PCI one. In order to overcome this limitation, we can't use `vfio-user` as it exposes the emulated device as a PCI device.
But there's a recent addition to the virtio spec called [virtio i2c](https://raw.githubusercontent.com/oasis-tcs/virtio-spec/master/virtio-i2c.tex), which would allow the device to be exposed on an i2c bus. And there's this `rust-vmm` effort to create a specific [vhost i2c crate](https://github.com/rust-vmm/vhost-device/pull/1) from the new spec. By supporting this, we could attach a `vhost-user-tpm` backend to it, and have it exposed on the i2c bus as expected.

**Comment by jlevon** [comment]
There's nothing specific to PCI in the vfio-user spec, for what it's worth. libvfio-user is based around PCI, certainly.

But I'm a bit confused as to the i2c bus comment. x86 guest side, the platform's TPM is just exposed as MMIO in ACPI, isn't that sufficient? Is this for aarch64, or something else?

**Comment by sboeuf** [comment]
>There's nothing specific to PCI in the vfio-user spec, for what it's worth. libvfio-user is based around PCI, certainly.

I know, but let's be honest, both VFIO and vfio-user have been designed with PCI in mind :)
Maybe the biggest example is the fact that the regions that are exposed are the BARs and the config space. I don't know how you would translate these if you wanted to expose your device through a different type of bus.

>But I'm a bit confused as to the i2c bus comment. x86 guest side, the platform's TPM is just exposed as MMIO in ACPI, isn't that sufficient? Is this for aarch64, or something else?

The problem with exposing a device directly through MMIO is that we would have to make it part of the Cloud Hypervisor device model. Instead, we simply want a way for our users to bring their own TPM emulation, based on some transport layer mechanism that we would provide.

**Comment by liuw** [comment]
> > There's nothing specific to PCI in the vfio-user spec, for what it's worth. libvfio-user is based around PCI, certainly.
> 
> I know, but let's be honest, both VFIO and vfio-user have been designed with PCI in mind :)
> Maybe the biggest example is the fact that the regions that are exposed are the BARs and the config space. I don't know how you would translate these if you wanted to expose your device through a different type of bus.
> 

If vfio-user can be extended to support arbitrary buses, that will be great.

> > But I'm a bit confused as to the i2c bus comment. x86 guest side, the platform's TPM is just exposed as MMIO in ACPI, isn't that sufficient? Is this for aarch64, or something else?
> 
> The problem with exposing a device directly through MMIO is that we would have to make it part of the Cloud Hypervisor device model. Instead, we simply want a way for our users to bring their own TPM emulation, based on some transport layer mechanism that we would provide.

There is still the part to generate ACPI table(s) for the TPM. Do you plan to rework the ACPI code to make it able to pull in tables from other sources?

There is no need to have a TPM emulator in Cloud Hypervisor. We had a smart and hardworking intern who implemented a prototype for TPM support. His design includes a small proxy inside Cloud Hypervisor. TPM emulation is done in another process by swtpm -- this is not unlike what QEMU does. The proxy forwards commands to the emulator via a socket. He got to the point that Linux was able to recognize there was a TPM but failed to initialize it due to timeout in the emulator, but he ran out of time to debug it further.

**Comment by sboeuf** [comment]
@liuw so this proxy code in Cloud Hypervisor takes care of placing a device on the MMIO address space?
About the ACPI part, that's tricky as it means we either need to know about the type of device that we're going to expose to guest (so that CH would take care of it), or it must be passed by the backend through the socket (which means we need some kind of protocol between the two).
The benefit of using a solution like virtio-i2c would be to avoid all the ACPI complexity as well as relying on a very well defined protocol (vhost-user) between the backend and the VMM.

**Comment by liuw** [comment]
> @liuw so this proxy code in Cloud Hypervisor takes care of placing a device on the MMIO address space?

Yes. It generates the required ACPI table and register an MMIO region.

> About the ACPI part, that's tricky as it means we either need to know about the type of device that we're going to expose to guest (so that CH would take care of it), or it must be passed by the backend through the socket (which means we need some kind of protocol between the two).

Right. And I would very much like to avoid inventing bespoke protocol for passing ACPI related information.

> The benefit of using a solution like virtio-i2c would be to avoid all the ACPI complexity as well as relying on a very well defined protocol (vhost-user) between the backend and the VMM.

This sounds interesting. I will check it out.

**Comment by liuw** [comment]
(Keep in mind I'm not an expert on TPM)

I checked out Linux's TPM drivers under drivers/char/tpm. It seems to me for TPM2 ACPI is mandatory. As for I2C based drivers, they look rather bespoke. Each vendor comes up with their own driver.

**Comment by jlevon** [comment]
> regions that are exposed are the BARs and the config space

Yep, though note they're `VFU_PCI_DEV_NUM_REGIONS`, a device with a different `vfu_dev_type_t` would have a totally separate region namespace (and might for example have region caps instead of integer namespace IDs. Not saying we wouldn't have work to do, but the framework should be there.

> directly through MMIO is that we would have to make it part of the Cloud Hypervisor device model
> must be passed by the backend through the socket (which means we need some kind of protocol between the two).

I think the qemu-style proxy talking SWTPM protocol *is* that, isn't it?

**Comment by t-seanyoo** [comment]
Hi everyone, I'm the intern mentioned above. So QEMU emulates a TPM TIS interface which is what I was able to do in Cloud Hypervisor. The interface is added as a part of the CLH device model which emulates registers + allocates MMIO region based on the interface specification from the TCG ([TCG TIS Specification](https://trustedcomputinggroup.org/wp-content/uploads/TCG_PCClientTPMInterfaceSpecification_TIS__1-3_27_03212013.pdf)). The exposure to the guest is through ACPI tables for TPM2 which as @liuw said is mandatory according to the TCG specification ([TCG ACPI Specification](https://trustedcomputinggroup.org/wp-content/uploads/TCG_ACPIGeneralSpec_v1p3_r8_pub.pdf)). Linux and Windows both have drivers for this interface. The interface forwards commands to the external TPM which is handled by the backend. The backend is essentially the proxy which can be adjusted to interact with any software TPM or passthrough since commands are pretty standard for TPMs ([TCG Commands Specification](https://www.trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf)) 

I implemented a solution with [swtpm](https://github.com/stefanberger/swtpm) and this approach seems to work. The TIS front end still needs to be debugged but the MMIO region is allocated appropriately and TPM2 is recognized by the guest before the TPM_TIS driver in Linux fails one of its checks due to timeout error and then Guest launches in TPM bypass mode. 

> The problem with exposing a device directly through MMIO is that we would have to make it part of the Cloud Hypervisor device model. Instead, we simply want a way for our users to bring their own TPM emulation, based on some transport layer mechanism that we would provide.

With this design, a backend module can be created and inserted into the architecture to forward commands to any TPM emulator as the commands sent to the backend are the standard TPM commands. The front end interface is the only part that needs the ACPI/MMIO exposure so this part is static and no ACPI has to be passed through the socket (not sure if this is even possible with swtpm).

The design I created in based off the QEMU approach and I created a design document with all the details which I will attach here: [CloudHypervisor_vTPM_Design_Doc.pdf](https://github.com/cloud-hypervisor/cloud-hypervisor/files/7019105/CloudHypervisor_vTPM_Design_Doc.pdf). 

Link to fork I was working on is here: [CLH vTPM Fork](https://github.com/t-seanyoo/cloud-hypervisor/tree/vTPM)

**Comment by rbradford** [comment]
@t-seanyoo Thank you for your work and for filling in these details. 

I think this approach is fine. I would expect this would be exposed to the user via `--tpm socket=<path>|fd=<fd>` and if that is present then the MMIO region would be exposed through ACPI and the device added to the MMIO bus. My expectation is that the ACPI entries are mostly static and just relying on the MMIO address. Is there anything in there that the VMM does not know? (i.e. I don't think we need a general approach to extend ACPI tables from outside.)

@liuw Are you or someone on your team going to continue looking at this?

**Comment by t-seanyoo** [comment]
@rbradford 

I wasn't able to configure the option parameter yet but yes that's exactly what I had in mind. 

ACPI tables are indeed static (only differ based on TPM 1.2 and TPM 2.0, or type of interface if alternatives are supported (see note) but this can be configured on the VMM side). No general approach to extend ACPI tables from outside is necessary from what I have learned.

@liuw is actually from a different team than the one I was assigned to and I believe the intention was for someone from my team to pick this up but unsure of when that would be. I will ask about this and get back to you.

Note: There are alternative interface specifications that exist like the one for [Physical Presence Interface](https://trustedcomputinggroup.org/resource/tcg-physical-presence-interface-specification/) and CRB interface which QEMU also gives the option for (although they aren't required). The Physical Presence Interface works with the TIS interface, and the [CRB](https://trustedcomputinggroup.org/wp-content/uploads/Mobile-Command-Response-Buffer-Interface-v2-r12-Specification_FINAL2.pdf) is an alternative to TIS directly (specifically designed for TPM 2.0 while TIS supports both 1.2 and 2.0). To add PPI ACPI to TIS or CRB ACPI table, a separate section is needed but this also can be static inside of VMM.

**Comment by liuw** [comment]
@t-seanyoo Thank you very much for your detailed input. I will  follow up internally regarding the next steps for this project.

**Comment by rbradford** [comment]
@liuw Any update on staffing this feature? If it's no longer important to you then we can go ahead and close.

**Comment by liuw** [comment]
Please keep it open. This project is to be looked at shortly during our internal planning exercise.

**Comment by praveen-pk** [comment]
Team, fyi, I will drive this feature forward.

**Comment by eKKiM1** [comment]
Any progress on this issue?

Are (live) migrations supported with vTPM?

**Comment by rbradford** [comment]
@praveen-pk Any update on this?

**Comment by praveen-pk** [comment]
@rbradford I am making progress on this, but have been a bit slow due to time-bound internship I am mentoring. I am hoping to send first version of this patch set in 2-3 weeks.

https://github.com/praveen-pk/cloud-hypervisor/commits/upstream/vtpm_module/prep has the latest updates.

**Comment by praveen-pk** [comment]
Quick update: I have a working version of vtpm driver with CRB interface. I am prepping the code for a PR, aiming to get initial version submitted by next week.

**Comment by praveen-pk** [comment]
https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4640 posted.
