### ISSUE TITLE
Refactor Windows integration tests

### ISSUE THREAD

**Issue by weltling** [cloud-hypervisor/cloud-hypervisor#2520]
The goals:

- <strike>Reduce code duplication</strike> See https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2531#issuecomment-832020702 on why it is not expedient right now.
- Implement `wait_vm_boot()` as suggested in https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2519#pullrequestreview-642484064</strike>
- Don't wait for a fix time for image boot, see how polling can be implemented
- <strike>Allow for parallel test execution</strike> Fixed by #2599

**Comment by likebreath** [comment]
@weltling Thanks for opening the issue, and start to track on the refactoring. :)

To clarify a bit, we should not need to reimplement  `wait_vm_boot()` for Windows guests, or even we may not have to change its current implementation [here](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/test_infra/src/lib.rs#L46). I believe the major missing bit is an appropriate previsioning on the Windows guest, so that the guest will send a TCP package to the host (on a guest-unique port) once it is booted. We are doing this provisioning for Linux guests through [cloud-init](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/test_data/cloud-init/ubuntu/user-data#L66-L72). I was wondering whether it is hard for Windows guests. 

Also, it would be good to run Windows tests in parallel. I may miss some context here about the challenges we have. Maybe it is also about Window guest provisioning?

**Comment by weltling** [comment]
Now recall also this #1891 - that's sure a deployment issue, but potentially also a generic issue. This needs to be tested properly.

Thanks
