### ISSUE TITLE
Review vhost-user-net control queue

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2562]
The control queue appears to be established on the VMM side. This seems peculiar as there are commands that can be run through the control queue that have to be done in the backend.

**Comment by rbradford** [comment]
Perhaps using the instructions in docs/vhost-user-net-testing.md to combine CH with OVS it can be checked if the backend side provides the control queue and thus the VMM side should not.

**Comment by sboeuf** [comment]
For information, I'm currently looking into this. This will require some prior refactoring of `virtio-devices/src/net_util.rs` so that it can then be moved to the `net_util` crate.
Once abstracted behind the crate, the code should be used from `vhost_user_net/src/lib.rs` in order to implement the control queue from the vhost-user-net backend.
And finally, we'll be able to remove the dedicated thread for the control queue from `virtio-devices/src/vhost_user/net.rs` code.
