### ISSUE TITLE
sgx: numa information 

### ISSUE THREAD

**Issue by mythi** [cloud-hypervisor/cloud-hypervisor#2757]
The latest SGX EPC allocator is NUMA aware but that results in the following errors when run in a guest without topology information available for the SGX EPC section ranges:

```
[    0.530449] sgx: EPC section 0x3ffff3fef000-0x3ffffbfeefff 
[    0.531047] sgx: [Firmware Bug]: Unable to map EPC section to online node. Fallback to the NUMA node 0. 
[    0.531058] sgx: EPC section 0x3ffffbfef000-0x3ffffffeefff
[    0.531390] sgx: [Firmware Bug]: Unable to map EPC section to online node. Fallback to the NUMA node 0.
```

add the possibility to specify numa information on the command line and pass the info via ACPI SRAT to guests.

**Comment by sboeuf** [comment]
I'll look into this next week!

**Comment by sboeuf** [comment]
Assuming we want to give full control to the user, we need to gather the info from the CLI about what's expected. We must find a way to list which EPC sections are attached to each NUMA node, and we must declare one new entry per section in the SRAT.

From a CH perspective, that means we have to create `id=` for `--sgx-epc`, so that we can reference these `id`s from the `--numa` parameter. Then it's just some internal handling to make sure the SRAT get extended with the proper entries.

@mythi does that match your expectations?

@rbradford what do you think about adding `id` to `--sgx-epc` and then add `sgx_epc_sections` to `--numa`?

On the other hand, if we want an easy/quick fix for this problem, we can also make sure to tie every SGX EPC section to the NUMA node 0 by default. Still need some internal code for implementing this but we wouldn't need any change on the CLI.

**Comment by rbradford** [comment]
> @rbradford what do you think about adding `id` to `--sgx-epc` and then add `sgx_epc_sections` to `--numa`?
> 

SGTM
