### ISSUE TITLE
Tie VFIO device to NUMA node

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#2759]
Support specifying the NUMA node when adding VFIO devices.

**Comment by sboeuf** [comment]
After some investigations, I realized it didn't make sense to allocate a specific PCI device to a specific NUMA node. Indeed, that would allow the user to attach two PCI devices on the same bus to two different NUMA nodes, which would be wrong as it is not how thing would work with real hardware.

We still need to make sure the PCI bus is attached to a specific NUMA node, otherwise the guest doesn't know the proximity domain for the bus. This is fixed by https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2766
