### ISSUE TITLE
Booting hypervisor seems to freeze

### ISSUE THREAD

**Issue by lonnietc** [cloud-hypervisor/cloud-hypervisor#2855]
Hello,

I have an AMD 64 bit system running Ubuntu 20.04 with KVM setup and enabled.

Followed the "2. Getting Started" steps from

https://github.com/cloud-hypervisor/cloud-hypervisor

Everything seems to go very smoothly until I get to the "Run" section and try to run the downloaded focal-server-cloudimg-amd64.raw image:

$ sudo setcap cap_net_admin+ep ./cloud-hypervisor/target/release/cloud-hypervisor
$ ./cloud-hypervisor/target/release/cloud-hypervisor \
	--kernel ./hypervisor-fw \
	--disk path=focal-server-cloudimg-amd64.raw \
	--cpus boot=4 \
	--memory size=1024M \
	--net "tap=,mac=,ip=,mask=" \
	--rng

At this point the system just seems to hang.

![Screenshot from 2021-07-12 07-40-11](https://user-images.githubusercontent.com/15264930/125281665-819e7b00-e2e4-11eb-9996-454e21c3b283.png)

Maybe this is what is supposed to happen, but it does not seem correct to me.

**Comment by sboeuf** [comment]
Hi! It might take some time for your guest to boot, but eventually you should see something like:
```
Ubuntu 20.04.2 LTS cloud hvc0

cloud login:
```

Are you sure you downloaded the latest version of the `hypervisor-fw` binary? Also, you can remove `--rng` since `virtio-rng` is enabled by default.
Last thing, run the same command line with `--serial tty --console off`, this should generate some useful output that might help us understand what's going wrong.
