### ISSUE TITLE
When host has no huge page, vm booted with hugepages will raise ReadKernelImage error

### ISSUE THREAD

**Issue by wfly1998** [cloud-hypervisor/cloud-hypervisor#2902]
**Describe the bug**

When host has no huge page, vm booted with hugepages will raise `ReadKernelImage` error.

**To Reproduce**

Set `nr_hugepages = 0`, then boot vm with "hugepages=on"

```bash
echo 0 > /proc/sys/vm/nr_hugepages
cloud-hypervisor \
        --kernel ./hypervisor-fw \
        --disk path=focal-server-cloudimg-amd64.raw \
        --cpus boot=4 \
        --memory "size=1024M,hugepages=on,hugepage_size=2M" \
        --net "tap=,mac=,ip=,mask=" \
        --rng
```

Then clh will raise error:

```
Error booting VM: VmBoot(KernelLoad(Elf(ReadKernelImage)))
```

But when set `/proc/sys/vm/nr_hugepages` to a suitable value, boot will succeed.

**Version**

```sh
$ cloud-hypervisor --version
cloud-hypervisor v17.0-3-g5bcbd560-dirty
```

This binary is cloned and compiled just now without changing.

**VM configuration**

My command line is the same as `README.md` except `hugepages=on,hugepage_size=2M` in `--memory`

And my Linux kernel is `Linux 5.10.52-1-MANJARO`

**Comment by wfly1998** [comment]
In addition, I traced the code and found that the problem may be located in the upstream crate `linux-loader` and `vm-memory` in `rust-vmm`.

**Comment by sboeuf** [comment]
Well that's not really an error since there's no hugepages available on the host. But I agree the error could be better in order to let the user know about the real issue.
Maybe we could check if there are enough hugepages available based on the user configuration before going further, what do you think @rbradford ?

**Comment by rbradford** [comment]
The documentation on huge pages clearly states that you must have enough huge pages assigned for your workload. Since page faulting happens on demand we cannot know where it will fail (if you have some but too few then it might fail at some random point in the execution of the guest.) Checking the number of huge pages at VM creation time is non-trivial and won't help if you have something else running that consumes huge pages (like a vhost-user DPDK backend.)

**Comment by sboeuf** [comment]
Ok so it seems there's not much we can do about it @wfly1998 
Feel free to close the issue if you feel we answered your questions.

**Comment by wfly1998** [comment]
Sorry, I didn't express it clearly. It's not really an error, but the message provided too little information. Because this is not the fault of image, but the fault of huge pages.

You know, when I encountered this error for the first time, I didn't know that the problem would be the lack of huge pages.

I think the code has no problem, but it is necessary to explain this in the documentation.

Anyway, thank you for your answer.

**Comment by sboeuf** [comment]
@wfly1998 that's actually a great idea to update the documentation. If you have some time to do so, we'll be more than happy to accept your PR :)
