### ISSUE TITLE
Add support for vhost-user behind virtio-iommu

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#3066]
This will improve security for vhost-user devices as they won't have full access to the guest RAM.

**Comment by sboeuf** [comment]
After some investigations based on the [vhost-user specification](https://github.com/qemu/qemu/blob/master/docs/interop/vhost-user.rst#iommu-support) and the QEMU codebase (`hw/virtio/vhost_user.c`, `hw/virtio/vhost.c`, and `hw/virtio/vhost-backend.c`), here is the list of things we need to complete this task:
- [ ] Add support for `VHOST_USER_IOTLB_MSG` to `Master` and `MasterReqHandler` in the [vhost](https://github.com/rust-vmm/vhost) crate.
- [ ] For each `vhost-user` device in Cloud Hypervisor, we must check the backend supports `VIRTIO_F_IOMMU_PLATFORM` feature when the device is placed behind a vIOMMU by the user. If that's not the case, we must throw an error.
- [ ] For each `vhost-user` device in Cloud Hypervisor, we must implement the slave request handler (which will be factorized through the vhost-user handler) when placed behind vIOMMU.
- [ ] About the vhost-user logic and how to use the `VHOST_USER_IOTLB_MSG` command, the VMM will be in charge of notifying `IOTLB_INVALIDATE` whenever an unmap will occur through the vIOMMU for the given device. And the `IOTLB_UPDATE` won't be initiated by the VMM. Instead, the backend will be sending a `IOTLB_MISS` whenever it needs access to a specific address range in memory, which will be checked by the VMM, and in case it is range that has been allowed through the vIOMMU, the VMM will issue an `IOTLB_UPDATE`.
- [ ] Add some integration testing using OVS-DPDK. Since DPDK is the only backend I could find implementing the vIOMMU support, we must be able to rely on this backend to validate the newly added feature.

**Comment by sboeuf** [comment]
Based on the way vIOMMU support is designed from a vhost-user specification perspective, it is not bringing any added security. The guest memory regions are still passed to the backend, by providing a file descriptor to access them. This means that even if we introduce the concept of IOTLB entries, we must always trust the backend for doing the right thing. If the backend was compromised, it could decide to access some unauthorized memory ranges by simply reading/writing the file descriptors related to the guest memory regions.
For these reasons, we don't see a need for implementing this feature, and unless someone comes later with a practical use case for it, we won't implement this feature.
