### ISSUE TITLE
Add support for SLIRP based networking

### ISSUE THREAD

**Issue by fabiand** [cloud-hypervisor/cloud-hypervisor#32]
I wonder if support for slipr (like through [libslirp](https://gitlab.freedesktop.org/slirp/libslirp) as used by [rootless-containers](https://github.com/rootless-containers/)) can be added in order to support mode which does not require CAP_NET_ADMIN capabilities.

**Comment by sboeuf** [comment]
Hi @fabiand,

Just to clarify, the CAP_NET_ADMIN caps is only needed when you expect the VMM to create the TAP interface for you. But in real life use case, I would expect the user to create the TAP interface so that our VMM does not need the mentioned caps.

Worth to mention that we're working on the support of network (and other devices) based on `vhost-user`. So we could definitely interface the VMM with a `vhost-user` daemon relying onto `libslirp`.

**Comment by fabiand** [comment]
> I would expect the user to create the TAP interface so that our VMM does not need the mentioned caps.

Great - I'm a little libvirt-biased and there this flow is not possible :) But yes, +1

> So we could definitely interface the VMM with a vhost-user daemon relying onto libslirp.

That is crazy just to think about :)

**Comment by sboeuf** [comment]
Closing this for now, feel free to reopen.
