### ISSUE TITLE
Multiple PCI segment on aarch64 enabling

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#3296]
This is currently disabled on the integration tests. The extra PCI segment state is communicated through the MCFG and DSDT tables so should work on aarch64 ACPI. However there appears to still be some gap.

**Comment by michael2012z** [comment]
We are on it.

**Comment by michael2012z** [comment]
Update:

Latest observations in debugging guest kernel:
* Hotplugging on PCI segment 0 is OK, but fails on other segments
* The failure was caused by an error in probing the device
* The probing failure was further caused by missing `msi_domain`
* The lack of `msi_domain` was related with missing `MSI Group Nodes` in ACPI IORT table

Our current IORT implementation only covers single PCI segment. Next I will update IORT code and test.

**Comment by MrXinWang** [comment]
FDT multiple PCI segments support: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/3391
