### ISSUE TITLE
How does cloud-hypervisor achieve live update?

### ISSUE THREAD

**Issue by Lxiaoyouling** [cloud-hypervisor/cloud-hypervisor#3406]
Cloud-hypervisor can achieve live update through local live migration, but it may consume an extra memory of vm memory size. 

I plan to follow the steps below to implement a live update:
(1) save vm config --> vm pause --> save snapshot --> get fd of ch_ram
(2) call execvp，start a new cloud-hypervisor process according to saved vm config and saved fd of ch_ram
(3) restore snapshot, resume

But in step (2) I have a problem, after I clear FD_CLOEXEC and execute execvp(), is my fd released? Can I still use this fd？
In C language, this fd can still be used.

Thanks for your answer！

**Comment by sboeuf** [comment]
IIUC the fd you're talking about is the file descriptor associated with the RAM region. This is held up by the corresponding `GuestMemoryRegion` through a `FileOffset` and then a `File` object. When the region is dropped (object is destroyed), the fd will be closed. One way to avoid that is by duplicating the fd (`libc::dup()`) and hold onto the fd until you recreate the new memory region. Only at this time you will pass the fd that you kept alive so that it can be mapped with the region.

**Comment by rbradford** [comment]
I don't think your `FD_CLOEXEC` approach won't work. I think the correct approach is to use the migration infrastructure and rather than send the memory directly over the socket instead send the FD over the socket.

**Comment by Lxiaoyouling** [comment]
> I don't think your `FD_CLOEXEC` approach won't work. I think the correct approach is to use the migration infrastructure and rather than send the memory directly over the socket instead send the FD over the socket.

Thank you very much for your answer. 
FD_CLOEXEC can work. I need to set --mem shared=on in the command line, then I can get the fd of the memory.
Your idea is very good. I think I can fork a child process, and then implement live update through the logic of live migration

**Comment by rbradford** [comment]
@Lxiaoyouling If you're interested your can follow #3566 for details of support for live VMM update.
