### ISSUE TITLE
Support ioeventfd with vfio-user devices

### ISSUE THREAD

**Issue by likebreath** [cloud-hypervisor/cloud-hypervisor#3940]
The `VFIO_USER_DEVICE_GET_REGION_IO_FDS` API from vfio-user spec provides a faster way for the guest to notify/write to the device regions without needing to trigger VMX exit by using `ioeventfd` and `ioregionfd`. Similar to what we already have for virtio devices in Cloud Hypervisor, we can gain performance improvements by using `ioeventfd` with applicable vfio-user devices.

**Comment by likebreath** [comment]
@tmakatos @jlevon Do you know whether there are any available vfio-user device/server that implements the counterpart of `VFIO_USER_DEVICE_GET_REGION_IO_FDS`? IIUC, I don't think the latest SPDK/NVMe vfio-user  supports this feature (as I don't see the nvmf server code utilizes [`vfu_create_ioeventfd()`](https://github.com/nutanix/libvfio-user/blob/master/lib/libvfio-user.c#L467) from `libvfio-user`).  Any suggestions? Thank you.

**Comment by jlevon** [comment]
@likebreath I'm afraid not. SPDK's use of vfio-user has no use for ioeventfd (since we need a payload), and we haven't yet had time to look at ioregionfd support, although we would like to.

So the only "consumer" right now is libvfio-user's own tests.

FWIW we are happy to consider API changes in this area if you find the need for your ioeventfd use case.

**Comment by rbradford** [comment]
@jlevon I guess without ioeventfd/ioregionfd the BARs for the NVMe device cannot be mapped into the guest address space as there would be no way to know if the NVMe queue needed a kick?

**Comment by rbradford** [comment]
If there are no devices supporting this right now I don't think we need to worry about implementing it.

**Comment by jlevon** [comment]
Sorry, @rbradford I didn't notice I'd not replied.

With SPDK, you can optionally map the nvme doorbells directly into the guest VM. You are correct in that case that you can't directly detect a doorbell write in that case - so this is only useful if SPDK is in polling mode and hence never needs to be woken up (it will check in a hard cpu loop)

If SPDK is run in event-driven mode, then by default, guest-mapping of nvme doorbells BAR region is disabled. In that case, then each doorbell write is a vfio-user socket message from cloud-hypervisor to SPDK. However, this is slow.

This is where ioeventfd comes in: we'd like to be able to use a faster mechanism instead of sending a full message over the socket. This works great for (say) virtio, but with nvme we have a problem: the doorbell write has a payload, but normal ioeventfd's do *not* - they're just a wakeup/kick mechanism.

This is why there's no current/public ioeventfd consumer in vfio-user.

However, we *do* have some in-progress work in this area, called "shadow ioeventfd" - the idea is that we write the payload to shared memory area as well as kicking an ioeventfd. See https://review.spdk.io/gerrit/c/spdk/spdk/+/15418

This requires kernel and other patches which are not upstreamed.

There is also "ioregionfd" - an ioeventfd with a payload - but again they're not upstreamed.

Just to be clear, not trying to argue this should be re-opened, just wanted to provide context.

**Comment by rbradford** [comment]
> However, we _do_ have some in-progress work in this area, called "shadow ioeventfd" - the idea is that we write the payload to shared memory area as well as kicking an ioeventfd. See https://review.spdk.io/gerrit/c/spdk/spdk/+/15418
> 
> This requires kernel and other patches which are not upstreamed.
> 
> There is also "ioregionfd" - an ioeventfd with a payload - but again they're not upstreamed.


Yup, I understand and i'm looking forward to ioregionfd as I think that will be a good solution for other similar problems too.
