### ISSUE TITLE
Assess and improve design regarding Arc<Mutex<>> instances

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#445]
It'd be worth taking the time to assess the code as it recently grown a bunch of `Arc<Mutex<>>` and `Arc<RwLock<>>` instances. There are some cases where it is absolutely needed, but for some other cases, it is only there because at some point we need two different threads to have access to the same piece of information, given that only one of the two will need this to be mutable.
There might be room for optimization, using some synchronization mechanism in order to copy over to the other thread the information it needs once we can make sure it is safe to copy it. The idea would be to give full ownership of a copy once we know we are not expecting things to change further. This would allow both threads to deal with fully owned structures, which means there would be no lock involved.

**Comment by sboeuf** [comment]
Just a note that using `ArcSwap<T>`, which is equivalent to `Atomic<T>` is a good solution for use cases where we know the Object `T` is very rarely updated.

**Comment by rbradford** [comment]
Using `ArcSwap` is only useful where you're happy to make a copy of the shared state and replace it inside. It's not so useful where you want to update live shared state which is where much of our use of `Arc<Mutex<T>>` comes from.

For this to be actionable we need some concrete examples where locks can be removed so that those examples can be used for find others. @sboeuf You opened this issue, do you have any specific ideas in mind?

**Comment by sboeuf** [comment]
Nothing from the top of my head, but out of the numerous `Arc<Mutex<T>>` we have in our codebase, maybe some are very rarely updated, hence it'd be nice not to have to lock every time we need access to the data it contains.
