### ISSUE TITLE
Ensure errors from virtio devices cause VM & VMM to shutdown

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#4462]
Otherwise we are left with the e.g. vCPU and VMM threads running but no disk threads. The correct thing happens if there is a `panic!()` but not with errors propagated up.

**Comment by liuw** [comment]
Have you considered using `panic=abort`? Something to consider if you don't care about unwinding.

**Comment by rbradford** [comment]
@liuw Unfortunately the panic! handling does the correct thing. It's when a `Result::Err` is returned that the threads do not exit.

**Comment by sboeuf** [comment]
Maybe we could modify [handle_event()](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/virtio-devices/src/epoll_helper.rs#L38) so that it expects a `Result` to be returned. And from [here](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/virtio-devices/src/epoll_helper.rs#L158) we would trigger a `panic!()` if the `Result` is an `Err`. This way we could keep propagating errors in the internal code of each handler, but the common code doing the right thing of triggering the panic.

Maybe a completely different approach would be to send an event to the vmm thread whenever the epoll handler receives an error from the underlying code. Then the vmm thread could shutdown the VM.

**Comment by rbradford** [comment]
> Maybe we could modify [handle_event()](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/virtio-devices/src/epoll_helper.rs#L38) so that it expects a `Result` to be returned. And from [here](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/virtio-devices/src/epoll_helper.rs#L158) we would trigger a `panic!()` if the `Result` is an `Err`. This way we could keep propagating errors in the internal code of each handler, but the common code doing the right thing of triggering the panic.
> 
> Maybe a completely different approach would be to send an event to the vmm thread whenever the epoll handler receives an error from the underlying code. Then the vmm thread could shutdown the VM.

Rather then generate a panic. I would like us to return a `Result` and if that result is an error write to `exit_evt` like the panic handler. The reason `handle_event` does not return a `Result` is that all the virtio device errors do not yet `impl Error` so they cna't be wrapped and preserving the source. The correct fix is either to drop all error handling that happens on a thread (and just panic) or `impl Error` for all the errors (via `thiserror`) and then the error can be propagated up. Since we have fuzzers it's probably best to do the latter otherwise they are unusable.

**Comment by liuw** [comment]
> @liuw Unfortunately the panic! handling does the correct thing. It's when a `Result::Err` is returned that the threads do not exit.

Indeed. I misread. Cloud Hypervisor itself does not have any `catch_unwind` call.

I'm going off on a tangent now -- if we want to always abort using `panic=abort` (at least in the release profile) can reduce the binary size quite a bit. CrosVM and Firecracker are doing the same.
