### ISSUE TITLE
serial --off

### ISSUE THREAD

**Issue by fazlamehrab** [cloud-hypervisor/cloud-hypervisor#4671]
**Describe the bug**
serial --off option keeps printing the following warning. 

```<vcpu0> WARN:vmm/src/vm.rs:423 -- Guest PIO read to unregistered address 0x3fd```

**To Reproduce**
Launch a VM with ```serial --off```.

**Version**
Output of `cloud-hypervisor --version`:
cloud-hypervisor v25.0-444-g76903e5f

Did you build from source, if so build command line (e.g. features):

**VM configuration**

What command line did you run (or JSON config data):
`cloud-hypervisor --cpus boot=1 --memory size=512M --kernel hypervisor-fw --disk path=osdisk.img path=cloudinit --serial off`

Guest OS version details:
Ubuntu 20.04.4 LTS cloud

Host OS version details:
Ubuntu 18.04.5 LTS

**Logs**

Output of `cloud-hypervisor -v` from either standard error or via `--log-file`:

Linux kernel output:

**Comment by liuw** [comment]
When you turn on serial, does the warning disappear? I cannot find code in CH which handles 0x3fd quickly.

**Comment by rbradford** [comment]
This it to be expected. With `--serial off` the serial device is not added to the I/O bus (with address 0x3f8) which means any writes by the guest to the serial port will result in the warning message that there is no device associated with that I/O port. Since you're booting with hypervisor-fw it prints some messages to the serial port which result in those warnings.

If you don't care about the serial but want to run something in the VM that might use the serial port then `--serial null` will attach a device to the bus at the I/O port but not output anything

**Comment by fazlamehrab** [comment]
@liuw, yes. If we enably serial with other mode, like `tty`, this warning disappear. 

@rbradford , thanks for the explanation. It makes sense to me. Does it also mean that the default mode for serial is `null`, not `off`?

**Comment by rbradford** [comment]
> @liuw, yes. If we enably serial with other mode, like `tty`, this warning disappear.
> 
> @rbradford , thanks for the explanation. It makes sense to me. Does it also mean that the default mode for serial is `null`, not `off`?

Yes, the default is `--console tty --serial null`
