### ISSUE TITLE
Consolidate aarch64 documentation into README/building.md/uefi.md

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#4984]
I think it should be possible to remove the aarch64 specific documentation by consolidating into the README, docs/building.md and also docs/uefi.md.

This would make the aarch64 experience on par with the x86_64.md one.

**Comment by rbradford** [comment]
@michael2012z or @MrXinWang is this something you would like to do?

**Comment by MrXinWang** [comment]
@rbradford Just had a chat with @michael2012z, I will do that later this week if you are not in a hurry.

**Comment by MrXinWang** [comment]
Hi @weltling, when I tried to work on the doc consolidation, I noticed that the Windows CI is currently running for AArch64 and it seems that we are not using https://github.com/cloud-hypervisor/edk2/commits/ch-aarch64 that contains the TPM patches, could you please kindly provide some hints about this? Why don't we need these TPM patches now?

Thanks!

**Comment by weltling** [comment]
@MrXinWang looks like i missed this. AFAIR there's no TPM specific test done on the Windows side and also wouldn't know if Windows would support the specific TPM device. If i don't err, the TPM device implemented in CH would be only relevant for Linux. Things wouldn't seem to have chanced since Dec.

Thansk
