### ISSUE TITLE
dbus support as an alternative external API

### ISSUE THREAD

**Issue by lperkov** [cloud-hypervisor/cloud-hypervisor#5230]
The project supports REST based external API for configuration as explained here:

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/docs/api.md

There are use-cases where having D-Bus API would be preferred way to orchestrate the Cloud Hypervisor. D-Bus is a message bus system used by Linux applications to communicate with one another. It provides a way for programs to interact with each other, allowing them to send messages, emit signals, and trigger events. In nutshell, it is an ideal way to provide inter-process communication.

Prior to sharing a pull request adding this new feature any feedback from the community would be greatly appreciated.

**Comment by likebreath** [comment]
Thank you for opening the issue. Can you share more on the use-cases you have in mind for the D-Bus APIs and why the RESTful API won't fit the need?

**Comment by lperkov** [comment]
D-Bus is an ideal choice for inter-process communication on Unix-like systems due to its flexibility and ease of use. It is more flexible than REST APIs over Unix socket. This is because it allows you to define custom interfaces and message types, which can be used to send more complex data than just simple strings.

Asynchronous communication is possible with D-Bus, and messages can be broadcast to multiple processes simultaneously. This can be convenient for subscribing to events, such as when a VM goes down or a new interface appears. A continuous pull of information from the REST API would be necessary to implement this today, which is neither convenient nor practical.

A further advantage of D-Bus is that it provides authentication and authorization mechanisms, as well as the ability to define who can interact with the cloud-hypervisor in a more advanced way than only by file-permissions.

Last but not least, it should be possible to create an API that is identical to, or very similar to, the existing ones, but with added benefits of tighter integration and event subscriptions not available with REST APIs.

If there are no objections, we would like to add a backend API based on the [zbus](https://gitlab.freedesktop.org/dbus/zbus/-/blob/main/README.md) D-Bus implementation.

**Comment by liuw** [comment]
@lperkov Who or what will be the users of this D-Bus API?

**Comment by rbradford** [comment]
I've used D-Bus lots in the past for integrating desktop/mobile applications with backend services. I've never seen D-Bus used in the cloud native space where JSON over HTTP is the norm. JSON encoding of API data has its limitations - no control of specific number data types but it's the direction the industry has taken.

Do you have an API consumer that would be better suited to D-Bus?

**Comment by lperkov** [comment]
@liuw Any application or daemon that uses the existing REST API today is eligible for this service. It could also cover any situation where it would be beneficial to have an interactive two-way communication session with the cloud hypervisor. With the D-Bus API, you can send messages to cloud hypervisors and receive event-driven responses without polling the cloud hypervisor's REST API (for instance, receiving notifications when VMs are shut down).

@rbradford It is true in principle, but that is not how cloud hypervisor works. Cloud hypervisor opens a local unix socket, over which one communicates via the REST API. If that really serves the purpose, why not use a TCP-based server instead?

A local unix socket (firecracker legacy approach) prevents remote authentication issues, some security risks, and accidental configuration mistakes. Although this method is useful, it is insufficient to provide API access that is more robust, flexible, and secure.

A nutshell summary of this discussion is that the arguments can be used as they would be in any unix socket vs. D-Bus debate. This is why I proposed adding a D-Bus API as an alternative to the existing API, so users would have the option to choose between the two (without stepping on anyone's toes).

**Comment by lperkov** [comment]
@liuw @rbradford are you okay with sending out RFC with D-Bus as additional API to the existing infrastructure?

**Comment by rbradford** [comment]
> @liuw @rbradford are you okay with us sending out RFC with D-Bus as additional API to the existing infrastructure?

Some questions I think you need to answer before you go ahead:

1. Do you have a consumer of this new API?
2. How are you going to unit test/integration test?
3. How is adding (and also potentially deprecation/removal) handled? (it's easy with a JSON dict)
4. Can the user mix & match the HTTP API and the d-bus API?
5. Are you going to be around for the long term to maintain this? (i.e. do you work for an organisation that requires this functionality?)

**Comment by lperkov** [comment]
Thank you for your patience. I had some (great!) personal developments which took up most of my time.

1. We will also create a Open Source CLI application as well that will consume this new API. Suggestions on the name, license, or other details are welcome.
2. This is an implementation detail. At a minimum, the patches will have test/integration as the project has today. In the absence of one, any suggestion is welcome and will be incorporated.
3. Considering this a detail of implementation, we will look into it and share more details in pull request.
4. Yes. One API does not exclude the other. Although, for our use-case we would make it possible to turn off the HTTP API and we would implement the same for D-Bus API. This way, end users will have the greatest degree of flexibility.
5. Yes. We already collaborate with Cloud Hypervisor member companies and LF on a variety of projects. Also, we have begun inquiries about how we ([Sartura](https://www.sartura.hr/)) can officially join this LF project.

In the hope that the above gives us satisfactory feedback and is sufficient to kick off the project, we will move forward.

**Comment by brkp** [comment]
Hello there! I started working on this item as discussed above. We were planning to use [zbus](https://gitlab.freedesktop.org/dbus/zbus) and [tokio](https://tokio.rs/) to provide the D-Bus API, do you maybe have any feedback on adding these dependencies? Any other suggestions would be welcomed.

**Comment by rbradford** [comment]
I think `tokio` is a dependency we've rejected in the past as it's considered very heavy.

**Comment by lperkov** [comment]
@rbradford did you ever consider https://github.com/tokio-rs/io-uring ?

**Comment by brkp** [comment]
Thanks for the feedback! Instead of using `tokio`, we went with [`futures-rs`](https://github.com/rust-lang/futures-rs) coupled with the [`blocking`](https://github.com/smol-rs/blocking) for calling the internal API from zbus' async context.

Since the Internal API is built on top of `std::sync::mpsc::{Sender, Receiver}` (those are `!Sync`), calling it from an async context is problematic as for example `response_receiver.recv()` would block the caller thread and not let the async executor drive other tasks.

Instead of going with the approach of refactoring the internal API to be built on channels that support asynchronicity, we went with the approach of using `blocking::unblock` for the initial PoC of this feature. I'd really appreciate some feedback on this approach.

**Comment by rbradford** [comment]
> @rbradford did you ever consider https://github.com/tokio-rs/io-uring ?

That crate is used for the virtio-block device.

**Comment by brkp** [comment]
We would like to update the maintainers and the broader community on the progress we have made over at #5306.

To summarize the main points of the PR:

* We decided to use `zbus` together with `blocking` and `futures`. We chose `zbus` because it is a pure Rust based solution with an active community. The `futures` dependency is required since `zbus` requires an async executor to be present. As for the `blocking` dependency, it is needed to call blocking code (internal API in our case) from an async context.

* As JSON is tightly coupled to the project, the D-Bus API consumes and returns JSON data. This simplifies the implementation of tests and parameter addition/deprecation, as @rbradford noted. Other high-level interfaces that consume/produce JSON for the D-Bus API can be developed if desired.

* We have modified `ch-remote` to fully support the D-Bus API, simplifying the testing process. Consequently, if `ch-remote` supports a new API feature, it becomes very easy to test both APIs in integration tests. ([More details](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5306#issuecomment-1491677561))

* The aforementioned pull request already contains functioning tests, and we welcome any additional tests that the community may wish us to implement.

@likebreath @liuw @rbradford What do you guys think about the linked PR? I can split the PR into multiple ones if that's preferred.

**Comment by alyssais** [comment]
As a cloud-hypervisor user and occasional contributor, I feel a bit worried about this, due to its potential to increase the complexity and maintenance overhead of cloud-hypervisor.  It doesn't seem to have been explained _why_ cloud-hypervisor needs a D-Bus API.  If applications for some reason _must_ use D-Bus, wouldn't it be possible to implement a D-Bus API for cloud-hypervisor as an external process, that communicated with cloud-hypervisor over the existing API?  That would allow using D-Bus without having to have two APIs in cloud-hypervisor itself.

**Comment by alyssais** [comment]
> Specifically, we need verbose event logging and the ability to subscribe to these events, among other things.

Thank you for this context.  I hadn't seen before that the D-Bus API would have functionality not available over the REST API.

**Comment by lperkov** [comment]
This has been merged here https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5306
