### ISSUE TITLE
VM hangs at direct kernel boot on Hygon CPU

### ISSUE THREAD

**Issue by fengye87** [cloud-hypervisor/cloud-hypervisor#5305]
**Describe the bug**
When starting a VM on a bare metal server with Hygon CPU (using Virtink), the VM hangs at boot. After digging into kernel code, I found that the kernel stuck in an infinite [loop](https://github.com/cloud-hypervisor/linux/blob/ch-5.18.8/arch/x86/kernel/cpu/cacheinfo.c#L640). So I further extracted relate code, and tried to run it on the host, it exited the loop normally. Below is the related code:

```C
#include <stdio.h>
#include <stdint.h>

static inline void native_cpuid(unsigned int *eax, unsigned int *ebx,
                unsigned int *ecx, unsigned int *edx)
{
    /* ecx is often an input as well as an output. */
    asm volatile("cpuid"
        : "=a" (*eax),
          "=b" (*ebx),
          "=c" (*ecx),
          "=d" (*edx)
        : "0" (*eax), "2" (*ecx)
        : "memory");
}

#define __cpuid            native_cpuid

static inline void cpuid_count(unsigned int op, int count,
                   unsigned int *eax, unsigned int *ebx,
                   unsigned int *ecx, unsigned int *edx)
{
    *eax = op;
    *ecx = count;
    __cpuid(eax, ebx, ecx, edx);
}

enum _cache_type {
    CTYPE_NULL = 0,
    CTYPE_DATA = 1,
    CTYPE_INST = 2,
    CTYPE_UNIFIED = 3
};

union _cpuid4_leaf_eax {
    struct {
        enum _cache_type    type:5;
        unsigned int        level:3;
        unsigned int        is_self_initializing:1;
        unsigned int        is_fully_associative:1;
        unsigned int        reserved:4;
        unsigned int        num_threads_sharing:12;
        unsigned int        num_cores_on_die:6;
    } split;
    uint32_t full;
};


void main() {
    unsigned int        eax, ebx, ecx, edx, op;
    union _cpuid4_leaf_eax    cache_eax;
    int             i = -1;
    op = 0x8000001d;

    do {
        ++i;
        /* Do cpuid(op) loop to find out num_cache_leaves */
        cpuid_count(op, i, &eax, &ebx, &ecx, &edx);
        cache_eax.full = eax;
        printf("LOOP %d: %u\n", i, eax);
        printf("type %d\n", cache_eax.split.type);
        printf("level %d\n", cache_eax.split.level);
        printf("is_self_initializing %d\n", cache_eax.split.is_self_initializing);
        printf("is_fully_associative %d\n", cache_eax.split.is_fully_associative);
        printf("reserved %d\n", cache_eax.split.reserved);
        printf("num_threads_sharing %d\n", cache_eax.split.num_threads_sharing);
        printf("num_cores_on_die %d\n", cache_eax.split.num_cores_on_die);
        if (i > 100) {
            break;
        }
    } while (cache_eax.split.type != CTYPE_NULL);
}
```

**To Reproduce**
The issue can be easily reproduced with Virtink on a Hygon CPU machine.

1. Install K8s on the Hygon machine
2. Install Virtink on the K8s cluster
3. Create a Virtink sample VM

However, since this issue only exists on Hygon machines, which are rare in the market, so I'm afraid we can only analyse the problem here and I can help verify it.

**Version**

Output of `cloud-hypervisor --version`: v30.0

**Comment by liuw** [comment]
@weltling Does this look similar to you? We discussed in the past that the leave levels look wrong. This is on KVM too.

**Comment by weltling** [comment]
@liuw Yeah, this looks similar. Several specific points here to make a diff are:

1. The leaf in question is the one related to the CPU cache
1. The processor is AMD based

On my side I was focused on the Intel specific leafs till now, AMD would be next on the plate right after. Anyway, in the issue we've discussed previously, it turned out that the subleaf values were passed for the interception with an option that allowed to overwrite all subleafs. This confused the userspace tools, but not the kernel.

For this specific case, the observations i have are these:

- In CH, there's currently no infrastructure to pass the CPU cache configuration
- The CPU cache configuration correlates with the topology configuration
- In CH, I don't see the infrastructure to set topology for AMD based processors, so this seems to be rather KVM specific as if no topology is passed it's up to KVM
- Also, not least is the fact that Hygon, while AMD based, might still have some missing functionality or gaps

We could try to reproduce this on an AMD machine, if we knew which AMD processor version would correspond the particular Hygon and we'd also have such an AMD machine. I guess this mapping might be hard to satisfy. Though, if there's some specific documentation, we might make use of it to at least verify what is expected, @fengye87 perhaps you could link to some? 

At this point, it seems there are similarities but i don't see an immediate indication i could start with right now. 

Thanks

**Comment by liuw** [comment]
I'm just wondering if this is due to a lack of support on the AMD side. If this never worked before then it is not really a regression.

**Comment by fengye87** [comment]
@weltling It's a Hygon C86 CPU, here's what I can find about this CPU:

> The Hygon C86 is essentially an AMD EPYC Zen 1 chip with an additional cryptographic layer added by the Chinese joint venture company collaborating with AMD.

I'm afraid there's very little documentation about this CPU. I used AMD's manual when digging this problem.

**Comment by liuw** [comment]
Probably try the same program on an AMD machine? If the behaviour is the same then probably it is easier to fix that on AMD first.

**Comment by fengye87** [comment]
@liuw I've just tried the same program on an AMD EPYC 7262 8-Core Processor machine, it didn't encounter this problem. Since this is the only AMD machine I have access for now, I'm not sure if the behaviour is the same on all AMD machines. But I think a good chance is that Hygon is different from AMD on this problem :(

**Comment by weltling** [comment]
What I'm accessing is AMD EPYC 7763, looks like there's no much difference to expect :/ 

@fengye87 i'd still ask you to show the particular Cloud Hypervisor command line. And also, is the issue same when using hypervisor-fw or EDK (both are available from our repos)? A bare command will still be relevant when looking into it.

@liuw this issue indeed doesn't sound like a regression.

Thanks

**Comment by fengye87** [comment]
@weltling The command line I was using:`./cloud-hypervisor-static --kernel /tmp/vmlinux --cmdline "console=ttyS0 root=/dev/vda rw" --memory size=1073741824 --disk id=ubuntu,path=/tmp/rootfs.raw`. The issue is the same when using hypervisor-fw, the command line was: `./cloud-hypervisor-static --kernel /tmp/hypervisor-fw --memory size=1073741824 --disk id=ubuntu,path=/tmp/jammy-server-cloudimg-amd64.raw`

**Comment by liuw** [comment]
> @liuw I've just tried the same program on an AMD EPYC 7262 8-Core Processor machine, it didn't encounter this problem. Since this is the only AMD machine I have access for now, I'm not sure if the behaviour is the same on all AMD machines. But I think a good chance is that Hygon is different from AMD on this problem :(

Oh, bummer. Hygon should give you a manual then.

**Comment by rbradford** [comment]
Any update on on this?

**Comment by rbradford** [comment]
No updates on an old issue.
