### ISSUE TITLE
aarch64: Balloon fails on 64KiB page size system

### ISSUE THREAD

**Issue by peng6662001** [cloud-hypervisor/cloud-hypervisor#5369]
I run a VM with the following command on Ampere Altra:
```
"target/aarch64-unknown-linux-gnu/release/cloud-hypervisor" "--cpus" "boot=2,max=4" "--memory" "size=512M,hotplug_size=8192M" "--kernel" "/root/workloads/CLOUDHV_EFI.fd" "--cmdline" "root=/dev/vda1 console=hvc0 rw systemd.journald.forward_to_console=1" "--disk" "path=/root/ch_files/osdisk.img" "--disk" "path=/root/ch_files/cloudinit" "--net" "tap=,mac=12:34:56:78:90:01,ip=192.168.1.1,mask=255.255.255.0" "--balloon" "size=0" --api-socket /tmp/cloud-hypervisor.sock --log-file ch.log -v -v -v
```
The command comes from test_memory_hotplug in `tests/integration.rs`

Then I run command on host:
```
./target/aarch64-unknown-linux-gnu/release/ch-remote --api-socket /tmp/cloud-hypervisor.sock resize --balloon 4096
```
The VM crashes.
There is no problem if I use a number less than 4096 for "--ballon" option.

**Version**
Output of `cloud-hypervisor --version`:
cloud-hypervisor v31.0-5-g3f5dac98-dirty

Guest OS version details:
6.2.0+

Host OS version details:
6.3.0-rc4

**Logs**
Please check the log:[ch.zip](https://github.com/cloud-hypervisor/cloud-hypervisor/files/11217442/ch.zip)

**Comment by liuw** [comment]
You have some local modifications. Please make sure the tree is clean. We cannot possibly know what your local modifications are.

This looks interesting in the log:

```
cloud-hypervisor: 95.194160s: <__balloon> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(Failed to signal used inflate queue: MadviseFail(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))
cloud-hypervisor: 95.194294s: <vmm> INFO:vmm/src/lib.rs:1752 -- VM exit event
```

**Comment by peng6662001** [comment]
Hi @liuw :
The result is always fail when run `./scripts/dev_cli.sh tests --integration -- --test-filter test_memory_hotplug` with a clean and latest tree.
Then I add some log to print ssh commands and ch-remote commands.
```
cmd = "target/aarch64-unknown-linux-gnu/release/ch-remote",args = CommandArgs { inner: ["--api-socket", "/tmp/chVioJ1O/cloud-hypervisor.sock", "resize", "--balloon", "536870912"] },ret = true
ssh:command = grep MemTotal /proc/meminfo | grep -o "[0-9]*",ip = 192.168.1.2


==== Start ssh command output (FAILED) ====

command="grep MemTotal /proc/meminfo | grep -o "[0-9]*""
auth="PasswordAuth {
    username: "cloud",
    password: "cloud123",
}"
ip="192.168.1.2"
output=""
error="Connection(Os { code: 110, kind: TimedOut, message: "Connection timed out" })"
```

**Comment by adamliyi** [comment]
Hi @michael2012z , I did some debug: bellow error happens with 64KB host OS page size. 4KB page size work fine:

```
cloud-hypervisor: 95.194160s: <__balloon> ERROR:virtio-devices/src/thread_helper.rs:55 -- Error running worker: HandleEvent(Failed to signal used inflate queue: MadviseFail(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }))
```
In function **balloon::BalloonEpollHandler::process_queue()**,  we use **VIRTIO_BALLOON_PFN_SHIFT** to make memory range address align to PAGE_SIZE. But **VIRTIO_BALLOON_PFN_SHIFT** is hard-coded to 12.

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/main/virtio-devices/src/balloon.rs#L196
```
// Size of a PFN in the balloon interface.
const VIRTIO_BALLOON_PFN_SHIFT: u64 = 12;

virtio_devices::balloon::BalloonEpollHandler::process_queue():

      let range_base = GuestAddress((pfn as u64) << VIRTIO_BALLOON_PFN_SHIFT);
      let range_len = 1 << VIRTIO_BALLOON_PFN_SHIFT;

165             Self::advise_memory_range(memory, range_base, range_len, libc::MADV_DONTNEED)
133             unsafe { libc::madvise(hva as *mut libc::c_void, range_len as libc::size_t, advice) };
(gdb) p/x hva
$5 = 0xfffeefeb5000  <---- not align to 64KB (0x10000)
(gdb) p/x range_len
$6 = 0x1000
```

Kernel **do_madvise()** checks for page alignment: https://github.com/torvalds/linux/blob/master/mm/madvise.c#L1410
```
	if (!PAGE_ALIGNED(start))
		return -EINVAL;
	len = PAGE_ALIGN(len_in);
```

**Comment by rbradford** [comment]
I just checked the virtio spec - the page size for virtio-balloon is hardcoded as a 4k page. But as you say the kernel checks for system page alignments. There are probably quite a few other places that assume 4k page sizes.

**Comment by BlueSeaSailor** [comment]
We recently encountered the same balloon problem on the arm64 KB platform. We tried to solve this problem, but currently it can only support 64KB, which is a problem. I am glad that the community has noticed this problem. We tested the patch you mentioned, but found several problems.

self.bitmap & (bp_num_per_page - 1) == bp_num_per_page - 1, this code cannot count up to 16 (0-15), usually it will be full after just counting 4 times. So we recommended to modify it to let bp_num_per_page: u64 = ( 1 << (page_size >> VIRTIO_BALLOON_PFN_SHIFT)) - 1;

  self.bitmap & bp_num_per_page == bp_num_per_page;
if addr != self.addr {

     return false;
 }
addr should be aligned with page_size first, otherwise this place will return false directly, and I think it should return true instead of false, otherwise the function continue in the following code will be called consistently.

if !pbp.bitmap_full(range_base.0, page_size) {

      pbp.set_bit(page_size, range_base.0);
      return Ok(());
  }
We found that pbp.set should be executed before pbp.bitmap_full, otherwise it will never be called. It is a question of counting from 0 or counting from 1.

// SAFETY: FFI call. Trivially safe.

  let page_size: u64 = unsafe { sysconf(_SC_PAGESIZE) as u64 };
  if pbp.addr == 0 {
      pbp.addr = range_base.0 & !(page_size - 1);
  }
  if !pbp.bitmap_full(range_base.0, page_size) {
      pbp.set_bit(page_size, range_base.0);
      return Ok(());
  }
  pbp.clear_all();

 Before pbp.clear_all is executed, range_base.0 needs to realign page_size, otherwise in 64KB, it will report an error, and the corresponding memory slot cannot be found in region. 
       memory.find_region(range_base).ok_or(Error::GuestMemory(
      GuestMemoryError::InvalidGuestAddress(range_base), .
When we execute the balloon command, the VM will suddenly hang up.

I find that it is usefull just when the Host and guest have the same page size , whether we have the plan to consider the situation that the page size of the guest and host is different. I think it is difficult when the page_size if different.

We are still analyzing this problem and hope you have good suggestions.

**Comment by jongwu** [comment]
> @jongwu. I rebuild the patch and test it on my machine, but I found it may have some mistakes.
> 
> 1. The guest kernel memory size(free -h) could change after the balloon instruction has been executed, however, the host memory size layout(free -h) has no change. That's to say, the advise system call has not been called.
> 2. self.bitmap & ((1 << bp_num_per_page) - 1) == (1 << bp_num_per_page) - 1
>    The initial value of   self.bitmap in release_memory_region function is 0 each time, so only one bit is 1 when set_bit, so the self.bitmap & ((1 << bp_num_per_page) - 1) == (1 << bp_num_per_page) - 1 could not realize the target for counting.
> 3. pbp.addr = (range_base.0 + page_size - 1) & !(page_size - 1);
>    I think the pbp.addr should be down aligned not up aligned. pbp.addr = range_base.0 & (page_size - 1)
> 4. I don't really understand what this code means.
>    if !pbp.pfn_match(range_base.0) || pbp.hit_max(page_size) && !pbp.bitmap_full(page_size) {
>    // we are trying to free memory region in a different pfn with current pbp. Give up
>    pbp.reset();
>    return Ok(());
>    }

pfn_match is used for check if the region_base locates in the current pbp scope, if not, we should not continue to set bitmap.
hit_max seems not very useful, so, should be removed.

>    could you explain it? Or could we delete them.
> 
> 5. Self::discard_memory_region(memory, range_base, page_size as usize)
>    I think the rang_base.0 shoud be updated when the discard_memory_region is called.Because the
>    rang_base.0 almost is the 0xxxxf000 at the time，and let region =
>    memory.find_region(range_base).ok_or(Error::GuestMemory(
>    GuestMemoryError::InvalidGuestAddress(range_base), will report the InvalidGuestAddress
>    error.

I update the patch based on your comments.  I test for it. madvisor is called but I'm not sure if we can notice the change significantly in host as the kernel may not allocate as much memory as VM asks for. Usually only small piece of memory is allocated.

**Comment by jongwu** [comment]
Could someone help test [PR](https://github.com/cloud-hypervisor/cloud-hypervisor/pull/5459) on non-4k page size host?

**Comment by peng6662001** [comment]
@jongwu My config is CONFIG_ARM64_64K_PAGES=y
The VM works fine with different ballon configrations.

**Comment by jongwu** [comment]
Thanks! @peng6662001
