### ISSUE TITLE
Windows tests consistently failing

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#5400]
```
[2023-04-22T07:01:08.091Z] <INSTANCE CLASSNAME="BLUESCREEN">
[2023-04-22T07:01:08.091Z] <PROPERTY NAME="STOPCODE" TYPE="string"><VALUE>"0x3E"</VALUE></PROPERTY>
[2023-04-22T07:01:08.091Z] </INSTANCE>
[2023-04-22T07:01:08.091Z] </BP>
[2023-04-22T07:01:08.091Z] 
!SAC>
[2023-04-22T07:01:08.091Z] MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED
[2023-04-22T07:01:08.091Z] 
[2023-04-22T07:01:08.091Z] 
[2023-04-22T07:01:08.091Z] 0xFFFFF80259A7D180
[2023-04-22T07:01:08.091Z] 0x0000000000000002
[2023-04-22T07:01:08.091Z] 0x0000000000000001
[2023-04-22T07:01:08.091Z] 0x0000000000000001
```

It looks like there was a change in the Azure VM environment that had lead to the fix needed in #5399 (with the initial apicid changing) and also now all the Windows tests failing.

**Comment by likebreath** [comment]
@liuw @weltling Can you please take a look and bring the Windows guest CI worker back? Thanks

**Comment by weltling** [comment]
Thanks for the heads up, @likebreath. I'm going to start digging on this, didn't realize the Windows guest CI is down. 

Thanks

**Comment by weltling** [comment]
I made a first step to verify the boot on the HW host and CH boots a Windows guest there without an issue. This seems to confirm that the issue is nested virtualization related. The change as mentioned in the description and the BSOD exception text seem to match the topic, as with APIC IDs naturally affect the multi processor configuration. I'll continue digging moving the investigation onto an Azure VM.

Thanks

**Comment by weltling** [comment]
I had another session to dig on this. In conjunction with the Azure VM generation, the issue seems to be related to `EDK2`, not CLoud Hypervisor. I'll go in more detail in further.

I tested on an der v4 generation of VMs, in particular used `Standard D32s v4`. All of `EDK2`, `hypervisor-fw` or `vmlinux` passed to `--kernel` seem to work as expected correspondingly with Linux/Windows guest.


Then I went to checking on `Standard D32s v5` and that's where issues do reproduce. The issue manifests itself only with multiprocessor configuration and EDK2 `ch-92c79b2901` which seems to be the one also used in the github actions CI. However, EDK2 doesn't seem to be involved in the tests extensively (please correct me if i'm wrong). Still, `hypervisor-fw` and `vmlinux` with a linux guest work here as expected doing the manual test, but `EDK2` seems to be currently going under the radar from the CI perspective.

Repro command with Windows guest:

`target/debug/cloud-hypervisor --cpus boot=4,kvm_hyperv=on --memory size=4G --kernel CLOUDHV.fd --serial tty --console off --disk path=windows-server-2022-amd64-2.raw,num_queues=4 -v`

The firmware shows a crash as below:
```
!!!! X64 Exception Type - 0D(#GP - General Protection)  CPU Apic ID - 00000000 !!!!
ExceptionData - 0000000000000000
RIP  - 000000000009F000, CS  - 0000000000000018, RFLAGS - 0000000000000008
RAX  - 0000000000000000, RCX - 00000000BFD4FDD4, RDX - 00000000BFD4FDD0
RBX  - 00000000BFD4FDCC, RSP - 0000000000000000, RBP - 0000000000000000
RSI  - 00000000BFD4FDDC, RDI - 0000000000000000
R8   - 0000000000000000, R9  - 0000000000000000, R10 - 00000000BFD4FE00
R11  - 0000000000000006, R12 - 0000000000000000, R13 - 0000000000000018
R14  - 0000000000000018, R15 - 0000000000010046
DS   - 000000000F8BFBFF, ES  - 0000000000000000, FS  - 00000000BFD4FD90
GS   - 00000000BFD4FE00, SS  - 0000000000000000
CR0  - 0000000000000000, CR2 - 000000000000001F, CR3 - 00000000BFF7B008
CR4  - 000000000000021F, CR8 - 0000000000000018
DR0  - 0000000000000000, DR1 - 0000000000800000, DR2 - 0000000000000228
DR3  - 0000000000000000, DR6 - 0000000000010046, DR7 - 0000000000000000
GDTR - 0000000000000008 0000000000000018, LDTR - 0000000000000008
IDTR - 0000000000000008 000000000000001B,   TR - 0000000000000008
FXSAVE_STATE - 00000000BFD4FA30
!! Ca!n!'!t!  fiXn6d4  iEmxagce eipnftoiromanti onT.y !p!!e!
- 06(#UD - Invalid Opcode)  CPU Apic ID - 00000002 !!!!
RIP  - 00000000BFF506EF, CS  - 00000000000000FF, RFLAGS - 0000000000010002
RAX  - 0000000000000000, RCX - 00000000000000FF, RDX - 00000000BFD4F6C9
RBX  - 00000000BFD4F79F, RSP - 00000000BFD4F7D8, RBP - 0000000000000002
RSI  - 0000000000000000, RDI - 0000000000000001
R8   - 0000000000000001, R9  - 0000000000000000, R10 - 0000000000000002
R11  - 00000000BFD4F820, R12 - 00000000BFD4F7DF, R13 - 00000000BFD4F701
R14  - 00000000BFD4F6D4, R15 - 0000000000000000
DS   - 00000000BFF51086, ES  - 00000000BFD4F660, FS  - 0000000000000002
GS   - 0000000000000008, SS  - 00000000BFD4F6A0
CR0  - 0000000080000013, CR2 - 0000000000000000, CR3 - 0000000000800000
CR4  - 0000000000000228, CR8 - 0000000000000000
DR0  - 0000000000000000, DR1 - 0000000000000000, DR2 - 0000000000000000
DR3  - 0000000000000000, DR6 - 00000000FFFF0FF0, DR7 - 0000000000000400
GDTR - 00000000004FFF00 000000000000001F, LDTR - 0000000000000000
IDTR - 00000000BFF7B008 000000000000021F,   TR - 0000000000000000
FXSAVE_STATE - 00000000BFD4F2F0
!!!! Find image based on IP(0xBFF506EF) /home/runner/work/edk2/edk2/Build/CloudHvX64/DEBUG_GCC5/X64/UefiCpuPkg/CpuMpPei/CpuMpPei/DEBUG/CpuMpPei.dll (ImageBase=00000000BFF50000, EntryPoint=00000000BFF54F14) !!!!
```


Repro command with Linux guest:

`target/debug/cloud-hypervisor --cpus boot=4,kvm_hyperv=on --memory size=4G --kernel CLOUDHV.fd --serial tty --console off --disk path=jammy-server-cloudimg-amd64-custom-20230119-0.raw,num_queues=4 -v`

The firmware shows a crash as below:
```
MpInitLib: Find 4 processors in system.
GetMicrocodePatchInfoFromHob: Microcode patch cache HOB is not found.
CpuMpPei: 5-Level Paging = 0
!!!! X64 Exception Type - 0E(#PF - Page-Fault)  CPU Apic ID - 00000003 !!!!
ExceptionData - 0000000000000000  I:0 R:0 U:0 W:0 P:0 PK:0 SS:0 SGX:0
RIP  - 0000000000000000, CS  - 0000000000000000, RFLAGS - 0000000000010002
RAX  - 00000000BFF7B008, RCX - 000000000000001F, RDX - 00000000004FFF00
RBX  - 0000000000000000, RSP - 0000000000000000, RBP - 0000000000010046
RSI  - 0000000000000000, RDI - 0000000000000228
R8   - 000000000000021F, R9  - 0000000000000508, R10 - 0000000000000008
R11  - 0000000000000008, R12 - 0000000000000008, R13 - 0000000000000008
R14  - 0000000000000018, R15 - 0000000000000008
DS   - 0000000000000000, ES  - 0000000080000013, FS  - 0000000000000400
GS   - 00000000FFFF0FF0, SS  - 0000000000800000
CR0  - 0000000080000013, CR2 - 00000048A7DBD404, CR3 - 0000000000800000
CR4  - 0000000000000228, CR8 - 0000000000000000
DR0  - 0000000000000000, DR1 - 0000000000000000, DR2 - 0000000000000000
DR3  - 0000000000000000, DR6 - 00000000FFFF0FF0, DR7 - 0000000000000400
GDTR - 00000000004FFF00 0000000000000000, LDTR - 0000000000000000
IDTR - 0000000000000000 0000000000000000,   TR - 0000000000000000
FXSAVE_STATE - 00000000BFD4F490
!!!! Can't find image information. !!!!
!!!! X64 Exception Type - 06(#UD - Invalid Opcode)  CPU Apic ID - 00000001 !!!!
RIP  - 0000000000000508, CS  - 0000000000000018, RFLAGS - 0000000000010046
RAX  - 0000000000000000, RCX - 00000000ABFA1AA8, RDX - 0000000000000002
RBX  - 00000000ABFA10D8, RSP - 00000000BFD4F8B0, RBP - 00000000BFD4FA90
RSI  - 0000000000000240, RDI - 00000000ABFA1AC8
R8   - 0000000000000000, R9  - 0000000000000000, R10 - 0000000000000000
R11  - 0000000000000000, R12 - 00000000BFD4FAC8, R13 - 00000000BFD4F9C0
R14  - 0000000000000006, R15 - 00000000ABFA1AA8
DS   - 0000000000000008, ES  - 0000000000000008, FS  - 0000000000000008
GS   - 0000000000000008, SS  - 0000000000000008
CR0  - 0000000080000013, CR2 - 0000000000000000, CR3 - 0000000000800000
CR4  - 0000000000000228, CR8 - 0000000000000000
DR0  - 0000000000000000, DR1 - 0000000000000000, DR2 - 0000000000000000
DR3  - 0000000000000000, DR6 - 00000000FFFF0FF0, DR7 - 0000000000000400
GDTR - 00000000004FFF00 000000000000001F, LDTR - 0000000000000000
IDTR - 00000000BFF7B008 000000000000021F,   TR - 0000000000000000

.......
```

Here, replacing boot CPUs with 1 fixes the issues in this constellation.

Conclusion: nested virtualization on Azure VMs of 5th generation, under KVM, seems to be broken with EDK2 fork for both Linux and Windows guest. 

I'm going to continue digging on this side, however my EDK2 experience is somewhat limited, so it will take some time. Any hints are appreciated from anyone with EDK2 expertise.

Thanks!

**Comment by rbradford** [comment]
@weltling They might also be failing due to edk2 issues but you can see that they did get further into the boot from the initial report which gives a bluescreen code.

**Comment by weltling** [comment]
@rbradford yeah, i was wondering why it didn't get through to the bluescreen part as well. But in any case it is something in APIC IDs that shows up as an issue.

Possibly it is still some VM size dependent diff. Which VM size is used by our CI? I should be able to replicate that one exactly, too.

Thanks

**Comment by rbradford** [comment]
> @rbradford yeah, i was wondering why it didn't get through to the bluescreen part as well. But in any case it is something in APIC IDs that shows up as an issue.
> 
> Possibly it is still some VM size dependent diff. Which VM size is used by our CI? I should be able to replicate that one exactly, too.
> 
> Thanks

D64s_v5 in the "West US" region.

**Comment by weltling** [comment]
Looks like the EDK2 symptom was secondary after all, the actual issue has been fixes in CH. It was still APIC ID related.

Thanks
