### ISSUE TITLE
network is not normal while run 2 iperf3 sessions with default queue size 256

### ISSUE THREAD

**Issue by bjzhjing** [cloud-hypervisor/cloud-hypervisor#570]
Start guest with 1 virtio-net device,1 single queue pair is defined, the queue size is with the default value, 256. Then, ssh from host, there will be two consoles opened for the guest, run the following iperf3 sessions on each of them.

```
host:  iperf3 -s 4444
guest:  iperf3 -c 172.100.0.1 -t 60 -i 2 -p 4444

host: iperf3 -s -p 6666
guest: iperf3 -c 172.100.0.1 -t 60 -i 2 -p 6666
```

Once the second session is started, one console is hang, and the throughput on the other one is zero. While if change the queue size to be 1024, both of the two sessions could  work normally .

**Comment by sboeuf** [comment]
That's really weird things get blocked with 256 while it works with 1024.
Could you try to reproduce the same thing without using `ssh`?
Just trying to eliminate potential issues coming from ssh using the same network interface.
BTW, do you create a dedicated virtio-net device for the ssh communication?

**Comment by sboeuf** [comment]
Just tried on my machine (based on `master` branch, which means queue size is `256` and num queues is 2 (1 pair)), and I cannot reproduce the issue.

Here are the steps for me:

Boot the VM:
```
./target/debug/cloud-hypervisor
    --disk path=clear-31310-kvm.img
    --kernel bzImage
    --cmdline "reboot=k panic=1 nomodules root=/dev/vda3 rw"
    --net "tap="
```
Assign an IP address for the network interface `enp0s3`, which allows me to ping the `vmtap0` created on the host by the VMM:
```
ip addr add 192.168.249.2/24 dev enp0s3
```
Create a script in the guest `net_test.sh`:
```
#!/bin/bash

iperf3 -c 192.168.249.1 -t 30 -p 4444 &
iperf3 -c 192.168.249.1 -t 30 -p 5555 &
iperf3 -c 192.168.249.1 -t 30 -p 6666 &
```
From the host, start my 3 servers from 3 separate terminals:
```
# From terminal 1
iperf3 -s -p 4444
# From terminal 2
iperf3 -s -p 5555
# From terminal 3
iperf3 -s -p 6666
```
And last step is to run the script from the guest after I made it executable:
```
chmod +x net_test.sh
./net_test.sh
```
I get the throughput effectively divided by 3 compared to the throughput I can reach with a single `iperf3` running, which is the expected behavior as we have three different `iperf3` instances sharing the same queues.

**Comment by bjzhjing** [comment]
> That's really weird things get blocked with 256 while it works with 1024.
> Could you try to reproduce the same thing without using `ssh`?
> Just trying to eliminate potential issues coming from ssh using the same network interface.
> BTW, do you create a dedicated virtio-net device for the ssh communication?

No, I do not create a dedicated virito-net device for ssh, it just shared the same one with iperf3 session. The same thing for 1024 buffer size.

**Comment by sboeuf** [comment]
@bjzhjing could you try creating a dedicated `virtio-net` device for the ssh communication? And also could you try the setup I described as it works fine for me?

**Comment by bjzhjing** [comment]
@sboeuf  I know why the error happens in my local test environment, since I use a relatively old linux kernel image for the test, version 5.0. I try the latest one, the error does not appear again. If no other comment, I think we could close this issue.
