### ISSUE TITLE
VFIO integration tests flake out regularly

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#5759]
I regularly see failures on the VFIO integration tests on main like this one: https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/job/cloud-hypervisor/job/main/550/execution/node/312/log/

```
11:21:57  + cp scripts/sha1sums-x86_64 /root/workloads
11:21:57  ++ curl --silent https://api.github.com/repos/cloud-hypervisor/rust-hypervisor-firmware/releases/latest
11:21:57  ++ grep browser_download_url
11:21:57  ++ grep -o 'https://.*[^ "]'
11:21:57  + FW_URL=
11:21:57  + FW=/root/workloads/hypervisor-fw
11:21:57  + '[' '!' -f /root/workloads/hypervisor-fw ']'
11:21:57  + pushd /root/workloads
11:21:57  + wget --quiet
11:21:57  ~/workloads /cloud-hypervisor
11:21:57  wget: missing URL
11:21:57  Usage: wget [OPTION]... [URL]...
11:21:57  
11:21:57  Try `wget --help' for more options.
11:21:57  
```

**Comment by rbradford** [comment]
My guess is that sometimes this machine fails to reach GH and so doesn't get a good URL.

**Comment by rmstoi** [comment]
This is due to GH rate limiting, occasionally I also get:

{"message":"API rate limit exceeded for 1.2.3.4 (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

To check rate limits run:
`$ curl -i https://api.github.com/repos/cloud-hypervisor/rust-hypervisor-firmware/releases/latest|grep rate`


For [unauthenticated requests,](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-personal-accounts
) the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the person making requests.

**Comment by likebreath** [comment]
@rmstoi  Any updates on this issue? It remains as one of the few issues causing main branch build to fail.
