### ISSUE TITLE
virtio-mem with vfio device (e.g. GPU Passthrough)

### ISSUE THREAD

**Issue by danielkrajnik** [cloud-hypervisor/cloud-hypervisor#5779]
@sboeuf @davidhildenbrand Sorry, this not a bug, but I saw that you tried to setup [vfio with virtio-mem](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1884). Have you every got it work? Does it really work like a memory balloon with vfio devices, e.g. a GPU Passthrough?

Any help would be really appreciated - you may be the only people on the face of this planet who have accomplished this!

**Comment by davidhildenbrand** [comment]
I test it with QEMU on a regular basis, and have some docs about that on the [development site](https://virtio-mem.gitlab.io/user-guide/user-guide-qemu.html). Regarding cloud-hypervisor: I never tried.

Regarding "Does it really work like a memory balloon with vfio devices, e.g. a GPU Passthrough?" -- while it shares some similarities with memory ballooning, it's a bit different -- the target use case is not optimizing memory overcommit but resizing VM memory. But yes, you can resize VM memory even when you have vfio devices attached that pin guest memory.

**Comment by danielkrajnik** [comment]
Thank you very much for your reply! That is really helpful.

> resizing VM memory

Does it mean that you can only do it manually and there are no automatic mechanisms? On libvirt for example you can only `virsh update-memory-device`. Is there no way to automate it like a virtio-balloon? If the guest at some point requests 10GB memory and later stops using them, is there no way to automatically release them back to the host?

**Comment by danielkrajnik** [comment]
For example, do you know by any chance what may be causing this command to still pinning over 9GB of RAM? I assumed that all the virtio-mem settings were "checked" already:

```sh
virt-install --name test --cpu cell0.cpus=0,cell0.memory=4194304,cell1.cpus=1,cell1.memory=4194304 --memory maxMemory=65536,maxMemory.slots=8 --memdev model=virtio-mem,target.node=0,target.block=2048,target.size=1000 --disk size=400 --network network=ai --location=/tmp/debian-12.1.0-amd64-netinst.iso --os-variant=debian11 --graphics none --extra-args "console=ttyS0"
```

**Comment by davidhildenbrand** [comment]
> Thank you very much for your reply! That is really helpful.
> 
> > resizing VM memory
> 
> Does it mean that you can only do it manually and there are no automatic mechanisms? On libvirt for example you can only `virsh update-memory-device`. Is there no way to automate it like a virtio-balloon? If the guest at some point requests 10GB memory and later stops using them, is there no way to automatically release them back to the host?

Yes, so far it's purely manual. Again, because the focus is not optimize memory overcommit where you usually try to dynamically (and with high frequency) shuffle memory around between VMs, to fake that you have more memory than you actually have.

The real problem about "requests 10GB memory and later stops using them" is when  the guest later wants to reuse that memory and you run out of memory in the hypervisor -- pinned pages cannot be swapped out, so if you cannot get memory back from other VMs fast enough, you have a problem.

If you own the VM and make the decision to take back memory from a VM (resize VM memory), knowing that the VM *won't* need that memory any-more, it's no longer memory overcommit.

Imagine virtio-mem like plugging/unplugging many virtual DIMMs. You wouldn't do that really to optimize for memory overcommit (cannot plug/unplug fast enough) -- and the VM really things that memory is gone for good once you unplug it.

> 
> Sorry again for being off-topic to the main project, but would you mind sharing your qemu (or ideally libvirt) configuration or a sample command that you used to run with viirtio-mem and vfio? I keep getting errors when trying to set it up with virt-install or libvirt's xml.

Probably best to discuss that offline. Can you send me a mail to david@redhat.com?
