### ISSUE TITLE
Backport security fixes to 37.x LTS release

### ISSUE THREAD

**Issue by skaegi** [cloud-hypervisor/cloud-hypervisor#6250]
We're using 37.0 and are hoping we could get a minor release bump to address https://github.com/advisories/GHSA-875g-mfp6-g7f9

Could https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6134 and possibly https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6141 be back-ported in a new minor release.

**Comment by likebreath** [comment]
@skaegi Yes, of course. That's on my todo list. The point releases are on hold due to major CI migrations that is ongoing (#6231). I will need to move backport these CI migrations along with the point releases also.

My plan is to have the point releases (for v37.x, v36.x and v28.x) next week. I will let you know when they are out. Thanks for waiting.

**Comment by likebreath** [comment]
@skaegi The backporting PR for v37.x is https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6272. We are working out a issue related to live-upgrade (due to kernel changes from the kvm-bindings crate). This should be resolved in the coming few days and you should expect to see the v37.1 release by end of this week.

**Comment by likebreath** [comment]
@skaegi The release is out https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v37.1. Thanks for the patience.
