### ISSUE TITLE
Docs about how to run a cloud-hypervisor VM with NVIDIA GPUDirect P2P needed 

### ISSUE THREAD

**Issue by Apokleos** [cloud-hypervisor/cloud-hypervisor#6305]
**Describe the bug**
It should not define it a bug, it's enhancement of cloud-hypervisor.

How to run cloud-hypervisor with NVIDIA GPUDirect P2P ? It lacks docs to help use such ability.

Thx

**Comment by rbradford** [comment]
@thomasbarrett Thanks to you we have this functionality - would you be up for enhancing the existing VFIO documentation?

**Comment by thomasbarrett** [comment]
Sorry, sat down to write this a few times. The TLDR is: when attaching a GPU as a VFIO device to a VM, you can specify the P2P clique ID of the GPU. 
```
--device path=/sys/bus/pci/devices/0000:01:00.0/,x_nv_gpudirect_clique=0
```

This informs the driver within the VM that the GPU is capable of talking to other GPUs in the same clique via PCIe P2P instead of shared memory. The following command can be used to validate that it is working:
```
nvidia-smi topo -p2p r
```

By default, I would recommend just putting all GPUs in P2P clique 0. If that doesn't work, depending on the server, it may be necessary to create multiple cliques. I don't believe that PCI root ports are required to support P2P traffic between them. _Some_ servers may only support P2P traffic between _some_ root ports.
