### ISSUE TITLE
Hypervisor trait

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#73]
In order to provide some abstraction over the type of hypervisor (KVM/hyper-v) being used, we should create an Hypervisor trait. This trait has to live into its own crate, and it would provide some implementation for KVM and Hyper-V I guess.

Just to clarify, we don't really need this trait/crate from a cloud-hypervisor perspective since we're not trying to support Hyper-V, but the goal is to be able to decouple some components such as the userspace IOAPIC from the knowledge about the type of hypervisor it's using.

**Comment by yisun-git** [comment]
Hi, Sebastien,

I have done this on rust-vmm. Please refer below link.
https://github.com/rust-vmm/community/issues/50

BRs,
Sun Yi

**Comment by sboeuf** [comment]
@yisun-git nice! I think that's what's needed long term.
Did you get some progress on the rust-vmm side of things?
I think once you get something merged into rust-vmm, we should port it to cloud-hypervisor.

**Comment by yisun-git** [comment]
On 19-06-24 08:43:27, Sebastien Boeuf wrote:
> @yisun-git nice! I think that's what's needed long term.
> Did you get some progress on the rust-vmm side of things?
> I think once you get something merged into rust-vmm, we should port it to cloud-hypervisor.
> 
I have finished draft codes based on Firecracker and uploaded the codes
to my personal github repo. Hypervisor crate depends on Vcpu crate which
was refused by community because Hyper-V and KVM have much different
vcpu exit reasons. So Hypervisor crate and Vcpu crate are pending issues
on rust-vmm now. Andreea was interesting to both crates. She asked me to
upload the draft codes to github. I do not know if she has finished
reading the codes. Hope she can have positive comment on both crates.

Another way to push the Hypervisor crate is to figure out another way to
handle vcpu exit reasons. I planned to do it when I am free. But it
seems I will not have free time recently.

**Comment by sboeuf** [comment]
I'm going to close this issue because the previous comment I left:
>Just to clarify, we don't really need this trait/crate from a cloud-hypervisor perspective since we're not trying to support Hyper-V, but the goal is to be able to decouple some components such as the userspace IOAPIC from the knowledge about the type of hypervisor it's using.

was suggesting I wanted to get rid of any KVM dependency from the IOAPIC implementation. Now that we have the InterruptManager, I can implement the IOAPIC without the explicit KVM dependency.

Let's close this issue, I'll take care of introducing the InterruptManager to the IOAPIC with a follow up PR.
