### ISSUE TITLE
tests::test_memory_overhead randomly failed

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#760]
Based on https://cloud-hypervisor-jenkins.westus.cloudapp.azure.com/job/cloud-hypervisor/job/PR-756/7/, we can see the integration test tests::test_memory_overhead randomly failed.

**Comment by rbradford** [comment]
@sameo I see a huge variation in values from test runs with this test. However these variations do not appear to be due to sampling error (i.e. if I sample in loop and compare the value to the previous value I get results that are stable.

Instead the instability comes across different runs of the same test on the same machine with the results fluctuating from 8328KiB to 10432KiB

Maybe the test methodology needs rethinking if we can see a 25% variance between runs.

**Comment by sameo** [comment]
@rbradford Could the variation come from the fact that this test is run in parallel with potentially many random other ones? What happens if we only run that test? Do we see a consistent and much less variable result?

**Comment by rbradford** [comment]
When I run the test on it's own on a dedicated machine I see the same variation.

**Comment by rbradford** [comment]
So we now have some added reporting and I can see that on runs where the tests fail the `anonymous` region is ~2KiB bigger. I think that this `mmap()` from `malloc()`

**Comment by sboeuf** [comment]
@rbradford could you elaborate?

**Comment by rbradford** [comment]
Removing the network interface and its unpredictable allocations (due to broadcast packets coming in) seems to have resolved this issue now.
