### ISSUE TITLE
Identify where unit tests can be added

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#78]
As the code base keeps growing, we need to take a moment to write some unit tests for the existing code.
I would expect this issue to stay opened long term, and instead please create some more fine granularity issues to explain which areas you tackled with the unit tests that you have implemented.

**Comment by rbradford** [comment]
@sboeuf Can you enumerate the locations where you think we could add more unit tests?

**Comment by sboeuf** [comment]
No this was more a reminder that we should write unit tests every it makes sense. I think there's nothing actionable here, hence this can be closed.

**Comment by sboeuf** [comment]
Issue has been repurposed.

**Comment by rbradford** [comment]
I think this issue can be closed. Having this issue here hasn't inspired any new unit tests to be written or even anyone to collate such a list. The nature of the project makes unit testing very difficult and I feel like that for the areas where we can do it e.g. config parsing, we already have good coverage.
