### ISSUE TITLE
Add EVENT_IDX support to virtio-block

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#786]
Our virtio-user-block backend  (see #774) now has support for using EVENT_IDX with some managed polling to improve performance. This could be extended to virtio-block.

**Comment by rbradford** [comment]
CC @slp

**Comment by slp** [comment]
@rbradford I thought this couldn't be done because all CH's internal devices were polled from a single event loop, but now I see each queue gets its own thread (not sure if this single event loop thing I had in my head comes from an earlier CH version or Firecracker, though).

Is there any circumstance in which a virtio-block queue would be polled from a non-dedicated thread? From a quick look at the code I'd say there isn't any, but I prefer asking just to be sure.

**Comment by rbradford** [comment]
>Is there any circumstance in which a virtio-block queue would be polled from a non-dedicated thread? From a quick look at the code I'd say there isn't any, but I prefer asking just to be sure.

@slp I'm pretty certain that that can't happen.

**Comment by slp** [comment]
@rbradford OK, then this should be easy.

**Comment by rbradford** [comment]
@slp Seems the code is already in crosvm - 2f7dabbd6a0d8620e4b19b92cdae24c08e4c7ccc
