### ISSUE TITLE
Default to backing memory with "/dev/shm"

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/cloud-hypervisor#862]
i.e. always pass the equivalent of `--mem file=/dev/shm`. This is necessary for anything using vhost-user to work and it's not immediately obvious why we wouldn't do it?

@sboeuf I know you have some thoughts on that, can you capu

**Comment by sboeuf** [comment]
The problem is that we still want a way to be able to run the VM without sharing its memory space with other processes on the host (other than the VMM's process). And I wonder how you're gonna be able to do so if you apply file=/dev/shm by default.
Do you expect that someone would run a VM with `--memory file=` to indicate that they don't want any backing file? The logic seems a bit reversed IMO.
Maybe we could add a boolean parameter saying `shared=on|off`, and that by default we would set this to `on`. And if no `file` is passed along with it, then we assume the default to be `dev/shm`.

**Comment by rbradford** [comment]
> The problem is that we still want a way to be able to run the VM without sharing its memory space with other processes on the host (other than the VMM's process).

Why? Is there a performance / security issue?

Wouldn't `file=/dev/zero` be okay to turn it off?

**Comment by sboeuf** [comment]
>Why? Is there a performance / security issue?

Well you're using a different `mmap` flags (`MAP_SHARED` vs `MAP_PRIVATE`), and in some contexts, some people might find some security issue with the fact that `MAP_SHARED` let other processes on the system get access to the VM's memory. That's why I still think we want to be able to let the user choose between the type of `mmap` involved.

**Comment by rbradford** [comment]
AFAIK `MAP_SHARED` requires the other process have the file descriptor so I don't really see the security implications?

**Comment by rbradford** [comment]
I don't think we're going to do this.
