### ISSUE TITLE
Virtio-mem kernel driver issue: virtio-mem driver may online the pages which are not plugged  

### ISSUE THREAD

**Issue by uMartinXu** [cloud-hypervisor/cloud-hypervisor#985]
online pages that are not plugged by hypervisor may cause a security issue.

Using steps below to reproduce the issue.
1. fix the issue#793 with PR# 984 https://github.com/cloud-hypervisor/cloud-hypervisor/pull/984
2. change below code and set
VIRTIO_MEM_DEFAULT_BLOCK_SIZE: u64 = (3 * 512 * 4096); // 6M 
notes: I did not find any comments that the block size has some limitations. 
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/6a934c32ee0d5a332998d38f1dc785854fca36d8/vm-virtio/src/mem.rs#L45
3. build  kernel and CLH
4. run CLH with below command
cloud-hypervisor \
	--kernel vmlinux \
	--console off \
	--serial tty \
	--disk path=clear-31890-kvm.img \
	--cmdline "memblock=debug loglevel=7 console=ttyS0 reboot=k panic=1 nomodules i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd root=/dev/vda3 memhp_default_state=online" \
	--cpus boot=1 \
	--memory size=1024M,hotplug_method=virtio-mem,hotplug_size=768M\
	--net "tap=,mac=,ip=,mask=" \
	--rng
3. check the current memory through /proc/meminfo
MemTotal:        1012316 kB
4. use below command to add 6M memeory 
curl -H "Accept: application/json" -H "Content-Type: application/json" -i -XPUT --unix-socket /run/user/1000/cloud-hypervisor.24467 -d "{  \"desired_ram\" : $(((1024 + 6)*1024*1024))}" http://localhost/api/v1/vm.resize
4. check /proc/meminfo
MemTotal:        1020508 kB
5. (1020508 - 1012316)/1024 = 8M it means 8M memory is added into buddy system and onlined after checking the kernel message, we can find only 6M memory actually plugged. So kernel driver online 2M more memory that is actually not plugged at all by hypervisor. 
it should be a kernel issue.

**Comment by rbradford** [comment]
Why would you change the constant VIRTIO_MEM_DEFAULT_BLOCK_SIZE?

**Comment by uMartinXu** [comment]
It is just used it to reproduce the kernel issue.
VIRTIO_MEM_DEFAULT_BLOCK_SIZE is the default "block size".
In theory,  Hypervisor can choose to use the different block size.
Kernel should work properly on different block size.
And here, if Hypervisor uses 6M as block size, kernel may have problem.

**Comment by Walnux** [comment]
https://github.com/cloud-hypervisor/linux/blob/dcfd4d5210e5193c6127ea463412bc0e98931790/mm/memory_hotplug.c#L556

**Comment by Walnux** [comment]
I got the chance to go through the kernel code to figure out the possible root cause of the issue.
see below code.
https://github.com/cloud-hypervisor/linux/blob/dcfd4d5210e5193c6127ea463412bc0e98931790/mm/memory_hotplug.c#L587-L612

https://github.com/cloud-hypervisor/linux/blob/dcfd4d5210e5193c6127ea463412bc0e98931790/mm/memory_hotplug.c#L604

call function in virtio-mem driver

https://github.com/cloud-hypervisor/linux/blob/dcfd4d5210e5193c6127ea463412bc0e98931790/drivers/virtio/virtio_mem.c#L816-L851

if the VIRTIO_MEM_DEFAULT_BLOCK_SIZE is 6M. 
according to code

https://github.com/cloud-hypervisor/linux/blob/dcfd4d5210e5193c6127ea463412bc0e98931790/drivers/virtio/virtio_mem.c#L1710-L1718

subblock_size is 6M

so subblock_size is not aligned with "2^(MAX_ORDER - 1) * page_size" if page size is 4K, it equals 4M.

So in this case
https://github.com/davidhildenbrand/linux/blob/b1f58684025b258b82fdaf6a674fe68b56527700/drivers/virtio/virtio_mem.c#L833

is actually be called twice with parameter order as MAX_ORDER - 1 and 8M memory is online.

**Comment by uMartinXu** [comment]
static int online_pages_range(unsigned long start_pfn, unsigned long nr_pages,
			void *arg)
{
	const unsigned long end_pfn = start_pfn + nr_pages;
	unsigned long pfn;
	int order;


	/*
	 * Online the pages. The callback might decide to keep some pages
	 * PG_reserved (to add them to the buddy later), but we still account
	 * them as being online/belonging to this zone ("present").
	 */
	for (pfn = start_pfn; pfn < end_pfn; pfn += 1ul << order) {
		order = min(MAX_ORDER - 1, get_order(PFN_PHYS(end_pfn - pfn)));
		/* __free_pages_core() wants pfns to be aligned to the order */
		if (WARN_ON_ONCE(!IS_ALIGNED(pfn, 1ul << order)))
			order = 0;
		(*online_page_callback)(pfn_to_page(pfn), order);
	}


	/* mark all involved sections as online */
	online_mem_sections(start_pfn, end_pfn);


	*(unsigned long *)arg += nr_pages;
	return 0;
}

**Comment by Walnux** [comment]
According to the below comments in virtio-mem driver

	/*
	 * We exploit here that subblocks have at least MAX_ORDER - 1
	 * size/alignment and that this callback is is called with such a
	 * size/alignment. So we cannot cross subblocks and therefore
	 * also not memory blocks.
	 */

subblock should have at least MAX_ORDER - 1 size/alignment. But looks like it is not assured or checked in the driver.

People can easily set the VIRTIO_MEM_DEFAULT_BLOCK_SIZE as 6M, which causes subblock_size not to be aligned with MAX_ORDER-1 size in Hypervisor and use it to exploit kernel.

So the possible solution might be checking the alignment of subblock_size.

**Comment by davidhildenbrand** [comment]
Hi,

the block size always has to be a power of two. This has to be guaranteed by the device and is e.g., checked in virtio-mem in QEMU since the very beginning.

I also documented that in the[ virtio-mem spec](https://lists.oasis-open.org/archives/virtio-comment/202005/msg00040.html) I sent out just recently.

_The device MUST set \field{block_size} to a power of two._

**Comment by Walnux** [comment]
@davidhildenbrand
Good to know that.
But I still think virtio_mem driver should check device_block_size when probing the device, in case a malicious Hypervisor uses it to exploit Host kernel.

the patch like below might be needed. 


```
diff --git a/drivers/virtio/virtio_mem.c b/drivers/virtio/virtio_mem.c
index 48e9670..35ed6e6 100644
--- a/drivers/virtio/virtio_mem.c
+++ b/drivers/virtio/virtio_mem.c
@@ -1648,11 +1648,18 @@ static int virtio_mem_init(struct virtio_mem *vm)
 		return -EBUSY;
 	}
 
+	virtio_cread(vm->vdev, struct virtio_mem_config, block_size,>
+		     &vm->device_block_size);
+
+	/* Check block_size and make sure it is the power of 2 */
+	if (!is_power_of_2(vm->device_block_size)) {
+		dev_err(&vm->vdev->dev, "block size is not power of 2\n");
+		return -EINVAL;
+	}
+
 	/* Fetch all properties that can't change. */
 	virtio_cread(vm->vdev, struct virtio_mem_config, plugged_size,
 		     &vm->plugged_size);
-	virtio_cread(vm->vdev, struct virtio_mem_config, block_size,
-		     &vm->device_block_size);
 	virtio_cread(vm->vdev, struct virtio_mem_config, node_id,
 		     &node_id);
 	vm->nid = virtio_mem_translate_node_id(vm, node_id);
```

**Comment by davidhildenbrand** [comment]
Hi,

No, if the device does not obey the spec it is broken and must be fixed. Otherwise we would not be able to trust anything the device does as a guest.

Also, I fail to see the security concern you mention. „Malicious hypervisor“ and „exploit host memory“ does nor make sense to me. If we have a malicious hypervisor we can easily have other issues.

**Comment by rbradford** [comment]
@davidhildenbrand The virtio-mem block size is a Po2 (and there is no user control for changing it). It's currently set to:

```
vm-virtio/src/mem.rs:pub const VIRTIO_MEM_DEFAULT_BLOCK_SIZE: u64 = 512 * 4096;
```

Is this a good choice?

**Comment by davidhildenbrand** [comment]
The QEMU code implementation documents:

"Use QEMU_VMALLOC_ALIGN, so no THP will have to be split when unplugging memory (e.g., 2MB on x86_64).". QEMU_VMALLOC_ALIGN in QEMU maps to 2MB on x86-64, a.k.a. THP size, just like the cloud-hypervisor implementation. We should avoid going smaller than the THP size (e.g., performance, but also due to memory consumption). The Linux driver currently supports 4MB blocks, with little effort, we can make also 2MB blocks work. Going smaller requires more work and might not actually be what we want (at least on x86-64, arm64 with 64k pages / 512MB huge pages is special ...).

**Comment by rbradford** [comment]
@davidhildenbrand Thanks, sounds good. I'm closing this issue as it is obvious that nPo2 block sizes are out-of-scope and we've got the correct choice of block size.
